### ISSUE TITLE
staff Recruit / permission

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#1]
- What happens? (please give a detailed explanation)
Staff recruit doesnt have access to /revive 
message output: Unsufficient permissions.
- What did you do to cause this?
Type in the different / commands such as /revive /dv
- Has it always been like this?
Nope
- What server version did this happen on?
6.0
- Please include a screenshot of your F8 console

**Comment by InZidiuZ** [comment]
This issue has been resolved. If the problem persists after the next update (6.0.1) please reopen the issue. For future reports, please use the appropriate template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
