### ISSUE TITLE
Suggestion for Phone.

### ISSUE THREAD

**Issue by Azacibran** [InZidiuZ/LegacyRP-feedback#10]
**Suggester:**
Aza Severide, Aza#0001
 
**Summary:**
Change the current ringtone to the original iPhone ringtone as the current one is crap.
 
**Reason:**
I don't think a serious person would have that ringtone, and it would be more good for the rp:ers.
 
**Economy:**
No, fortunately it won't.

**Comment by InZidiuZ** [comment]
Unless more feedback from other players are given, this suggestion will be disapproved.

**Comment by BOTMoffatto** [comment]
I would like to see this added, I do agree (even tho its quite goofy) the ringtone isn't realistic so having a variety of ringtones to choose from including possibly adding your own would be cool.

**Comment by shdwww** [comment]
I would like to have it added aswell. Just a plain iphone ringtone or anything.

**Comment by InZidiuZ** [comment]
Nokia ringtone? :)

**Comment by N8teZero** [comment]
I will take any ringtone over the current one, which sounds like you recorded yourself making ringtone sounds(you probably did tbh). Nokia ringtone it is!

**Comment by InZidiuZ** [comment]
Wow, why you gotta expose me like that!? 😢

**Comment by InZidiuZ** [comment]
Suggestion approved.
