### ISSUE TITLE
Car Liveries

### ISSUE THREAD

**Issue by ImAqux** [InZidiuZ/LegacyRP-feedback#100]
**Suggester:**
Who is suggesting this? Please include discord name.
#ImAqux#6284
 
**Summary:**
Write a short summary of what your suggestion is about.
Im basically suggesting that car liveries should be added, for two reason that is.
1. When you buy some cars from the dealership it will give you a car with a preassigned livery. (For example i bought a 100k rolls royce windsor and am not able to take the horrible livery off)
2. It will add more customization and make cars more unique and different.
 
**Reason:**
Why would your suggestion be a good addition to Legacy?
It will bring more addition to car meets and so that people are able to take off their livery's when they buy a car.
 
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope, Apart from people having to buy it but this is not really an impact.

**Comment by InZidiuZ** [comment]
Hi,

Car liveries is already a thing. However, there was previously an issue with them causing them not to stick after buying it. This has since been fixed, and will be patched with the next server restart.

**Best Regards,**
InZidiuZ
