### ISSUE TITLE
Bug: Performing animations while riding as a motorcycle passenger has undesirable effects

### ISSUE THREAD

**Issue by kinetixxx** [InZidiuZ/LegacyRP-feedback#101]
**Reporter:**
kin3tix#7292

**Summary:**
I don't recall exactly which one it was, however, while riding as a passenger on the rear of a motorcycle, I attempted to do an animation and the result was... odd. My character seemingly detached from the vehicle, however, my camera continued to follow the bike. After a few seconds, the bike started teleporting around and after a few more seconds, I was teleported to a beach quite a good distance from the bike. Then my game crashed shortly after.

**Steps to Reproduce:**
1. Be a passenger on a motorcycle while someone is driving
2. Hit F3
3. Select the jobs category
4. Try performing an animation

**Expected Results:**
I would guess animations shouldn't be possible while riding as a motorcycle passenger. :P

**Actual Results:**
A number of undesirable effects described in the summary.`

## More Info

**Screenshots:**
N/A

**Game Resolution:**
1920x1080

**Player Data:**
[EssentialMode] Version 6.1.0
[EssentialMode] Commands loaded: 43

**Comment by InZidiuZ** [comment]
This issue has been resolved. Animations are currently being redone and they will no longer be usable inside of vehicles. The new system will be pushed out with the next update.

**Comment by kinetixxx** [comment]
Excellent! Thank you for the update. ??
________________________________
