### ISSUE TITLE
Suggestion: Med Kits

### ISSUE THREAD

**Issue by WaldoMW** [InZidiuZ/LegacyRP-feedback#102]
Suggester: WaldoMW#1560

Summary: I think a Medkit would be a good addition to the server that can only be used when EMS aren't on or if wanted just use whenever but It would have a 4min use or something so that It can't be used during shootouts or middle of gun fights
Reason: I think we have 6 servers and not enough EMS to cover them all, and with these being public servers you sometimes get people that RDM or VDM and its heartbreaking on a lot of players to lose things over and over to those situations or when there is just no EMS on and you have everything on you.

Economy: It can depending on if you make it a only when no EMS are on thing or Perma thing, but I think it would effect it positively because it gives people something to buy that would be essential

**Comment by N8teZero** [comment]
While I do understand the idea of this, I don't believe we will be adding player medkits(revival kits) in the near future. We are actively working on preventing the underlying issue, RDM/VDM so as to prevent this needless deaths from occurring.

Thanks,
Nateღ - LegacyRP Staff & Developer
