### ISSUE TITLE
EMS F6 Menu new option to get people out of cars

### ISSUE THREAD

**Issue by JMcFluffy** [InZidiuZ/LegacyRP-feedback#103]
**Suggester:**
Who is suggesting this? Please include discord name.
_Lil TW#9255_

**Summary:**
_As a EMS i have to revive everyone or atleast try to help them, it sucks when i can't revive someone in a car. When someone is stuck in a car i can't revive them cuz the car is locked and i cant get them out. so i want a option in the F6 menu (Pull out of vehicle) for EMS._

**Reason:**
EMS cant reach the guy in the car

**Economy:**
_This will not change the Economy_

**Comment by N8teZero** [comment]
Duplicate of #129
