### ISSUE TITLE
illegal mods garage

### ISSUE THREAD

**Issue by JohnyDtv** [InZidiuZ/LegacyRP-feedback#104]
**Suggester:**
Johnyd#3182
**Summary:**
An illegal upgrades garage that you would go to for aftermarket parts that would include more engine mods turbo mods etc even body kits it would be like a little black market for car parts
**Reason:**
Due to my recent cop chase the cop let me know I would never be getting away from his vehicle as it was modded to hell and has a top speed of 350 that coming after the civ 116mph made a slow chase as one hit sent me flying, I think this would make for better rp as it would also enable a street racing scene to added to rp giving people more things to do in the city and help get the civs cars to more realistic speeds  it would also make people grind for the money a lot more to get that extra mod for the car 
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will? If the garage is city owned, then no

**Comment by johnnip** [comment]
i dont think any joe driving around on the street should be able to find/purchase these illegal mods, but i do agree with the main point of the suggestion that is illegal upgrades would be sick

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. Adding the ability for Mechanics to do the vehicle modding and tuning is something we want to do. No timeline for this yet, but it is on the list.

**Nateღ**
_Legacy RP Staff & Developer_
