### ISSUE TITLE
repair garage at sandy shores

### ISSUE THREAD

**Issue by JohnyDtv** [InZidiuZ/LegacyRP-feedback#105]
**Suggester:**
Johnyd#3182
**Summary:**
A garage at the sandy shores dirt race track where the fuel pump is also a little store there too

**Reason:**
This would enable race events to happen there with the option of repairing the cars at the garage so they can keep going and repair the minor damage, the store added would enable buying a repair incase of a total right off to the vehicle just make it so you cant rob it,

**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will? no

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
