### ISSUE TITLE
Taxi meter

### ISSUE THREAD

**Issue by basemas** [InZidiuZ/LegacyRP-feedback#106]
**Suggester:**
Parodax#6371
 
**Summary:**
As of right now when you open the taxi meter you have to start the meter with "K" but it will turn off the engine.
 
**Reason:**
unable to start the meter and drive the cab.
 
**Economy:**
no effect.

**Comment by N8teZero** [comment]
Great catch,

I've remapped the Taximeter controls to - and = for starting and resetting the meter. This should free up issues from other keybinds.

Thanks,
Nateღ - LegacyRP Staff & Developer
