### ISSUE TITLE
Cruise Control Issue

### ISSUE THREAD

**Issue by krakennnnn** [InZidiuZ/LegacyRP-feedback#108]
I press "x" to active Cruise Control and it says "Activated Cruise Control" then it doesn't do anything and my speed just goes down normally and doesn't lock the speed. I'm going over 35mph

**Comment by Anderzenn** [comment]
When you use cruise control it just locks your max speed to whatever speed you were at when you activated it. You still have to press W, it doesn't automatically drive your car at the speed.

**Comment by InZidiuZ** [comment]
Indeed, it's more of a "speed limiter".
