### ISSUE TITLE
Bugged Transport Jobs

### ISSUE THREAD

**Issue by GrandAct** [InZidiuZ/LegacyRP-feedback#109]
Reporter:
GrandAct
Ingame name: Hekter Grand
Discord name: Unique#3327

Summary:
1) If you spawn a trailer with a truck near (close but not inside) the spawn location, your truck will despawn. 

2) If you leave the trailer location and return, the trailer will sometimes not count as the designated trailer or will disappear altogtether

A way to respawn the trailer for the job, or a way to simply cancel the job i'm on and start a new one would be a simple solution to number 2

Steps to Reproduce:
1) Park a truck close to where the spawn location of a trailer is and spawn the trailer.

2) Spawn a trailer, leave general location for a few minutes and return.

Expected Results:
1) Trailer spawns on truck or spawns in a (more clearly) marked location.

2) Leave trailer, when you return you are able to deliver it.

Actual Results:
1) Truck disappears without a trace leaving me unable to deliver trailer, If I leave to get another truck bug number 2 will happen.

2) Trailer will either not be designated as deliverable, or will disappear completely.

**Comment by N8teZero** [comment]
Hey,

We've adjusted the spawns of trailers in known problem locations. If you find more, let us know.

**Nateღ**
_Legacy RP Staff & Developer_
