### ISSUE TITLE
Driver school if you fail you get stuck

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#11]
* What happens? (please give a detailed explanation)
If you fail the driver teori test you wont be apply to retake it, since it makes your screen freeze at the front page where you can press start.

* What did you do to cause this?
Take the teori test for driver school

* Has it always been like this?
  I am not sure to be honest
* What server version did this happen on?
  6.0
* Please include a screenshot of your F8 console

**Comment by N8teZero** [comment]
Hey,

Added blip for courthouse in the next update.

Nateღ
Legacy RP Staff & Developer
