### ISSUE TITLE
Characters sharing apartments

### ISSUE THREAD

**Issue by noreaga** [InZidiuZ/LegacyRP-feedback#111]
Reporter: Nore#8974

Summary: It appears that having multiple characters renting the same apartment overwrites one another. They seem to share the same inventory from the last character to rent it. 

Steps to Reproduce: I have two characters. One is a civilian which I had a bunch of things in it, including saved outfits and dirty money, etc. I created a 2nd character intended to be a police officer and rented the same apartment to save my LSPD outfit. Now both characters only show the saved LSPD outfit and nothing else. Seemed to have lost everything from my 1st character.

Expected Results: Having two separate apartment inventories

Actual Results: Sharing the same inventory

**Comment by noreaga** [comment]
EDIT: So I eventually logged on my LSPD character and they actually just swapped inventories. Weird...

**Comment by N8teZero** [comment]
Hey,

The housing inventory system has many bugs. We are working on transitioning to a new housing system, I am sure you've seen it, that should provide much better syncing of items across servers. It's still something we want to improve on more, so it will be on our list for the future framework.

**Nateღ**
_Legacy RP Staff & Developer_
