### ISSUE TITLE
Suggestion: More in depth emote system

### ISSUE THREAD

**Issue by noreaga** [InZidiuZ/LegacyRP-feedback#112]
Suggester: Nore#8974

Summary: I would love to see a bigger emote selection with the ability to use /e [emote] or /emote [emote] as opposed to the F3 menu. Maybe even the option to bind your favorite emotes on the FX keys.

Reason: Would provide more immersion and roleplay scenarios. Right now I feel the emote selection is very small for what is available out there.

Economy: No effect on economy.

**Comment by N8teZero** [comment]
Great suggestion,

We have some changes coming up that will improve the emote system and allow you to set "favorites" for common animations.

Thanks,
Nateღ - LegacyRP Staff & Developer
