### ISSUE TITLE
Suggestion: No damage for hydraulics

### ISSUE THREAD

**Issue by GrandAct** [InZidiuZ/LegacyRP-feedback#113]
Suggester:  Unique#3327

Summary: As it stands now if you buy a lowrider and use the hydrualics it will very quickly damage the car and cause it to smoke and become unusuable.
Possibly make the car not take damage (or greatly reduced) for a few miliseconds after hydraulics are used?

Reason: Would provide a better experience for roleplayers, as it stands now it is self defeating to purchase hydraulics.

Economy: More people purchase hydraulics

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
