### ISSUE TITLE
PD automatic timestamps

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#114]
**Suggester:**
Who is suggesting this? Please include discord name.
@Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.
Automatic timestamps

**Reason:**
Why would your suggestion be a good addition to Legacy?
So High command can easily see who is active and not. Avoid PD members to cheat their activity.

**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
No

**Comment by InZidiuZ** [comment]
Suggestion approved.
