### ISSUE TITLE
Robbery cooldown with a timer.

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#115]
**Suggester:**
Who is suggesting this? Please include discord name.
@Sercan#1192

**Summary:**
Write a short summary of what your suggestion is about.
A timer on the cooldown on robberies instead of just a message saying that there is a cooldown. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
To prevent planning alot and not knowing when you be able to rob. 

**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
Yes and no, People would know when they can rob which means that there would be more robberies, but in the other way people that plan alot and dont know when they can rob it risk such as server restarts ruin it.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. The robbery system will get some changes to make things much more user-friendly in the next framework.

**Nateღ**
_Legacy RP Staff & Developer_
