### ISSUE TITLE
Bug in Chop Shop

### ISSUE THREAD

**Issue by Littlearth2** [InZidiuZ/LegacyRP-feedback#116]
**Reporter:**
Who is reporting this? Please include discord name.

Littlearth
 
**Summary:**
Write a short summary of what you're experiencing.

I picked a car contract from the chop shop right before the server restart. After the restart i cannot pick a new one, i can not deliver the car that was prior to the restart either.
 
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

Not sure if we can reproduce it, but pick a contract, restart server, try to pick a new one.
 
**Expected Results:**
What are the expected results?

Expected results are to get a new contract, or be able do deliver the old contract
 
**Actual Results:**
What are the actual results?

Nothing happens, can't pick a new contract or deliver the old
 
## More Info
 
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
 
**Game Resolution:**
What is your game's resolution?

1920x1080 dx11 120Hz
 
**Player Data:**
Write /info whilst ingame and provide the information you're given.

Essentialmode Version 6.1.0
Essentialmode Commands Loaded: 43
 
**Notes:**
For anything else noteworthy.

**Comment by N8teZero** [comment]
Hey,

I'll take a further look into the chop shop and see if we can improve the way it handles contracts. I'll also be adding more vehicle selection and better payouts. The first iteration of the chopshop was a rough test of the system and aside from a few things here and there, it went well.

Thanks,
Nateღ - LegacyRP Staff & Developer
