### ISSUE TITLE
Bugs with phone

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/LegacyRP-feedback#117]
**Reporter:**
Brandon Whittle (Anderzenn#0069)

**Summary:**
Text messages received and sent shows as sent "1 hour ago" and if you re-log you can only see the messages you sent but not the ones you received and you're able to open the phone while you're "knocked out".

**Steps to Reproduce:**
First issue: Get a phone, send a text message to someone, it will say "sent 1 hour ago" or "received 1 hour ago" if you receive a text.
Second issue: re-log after receiving a text and you will only be able to see the texts you sent.
Third issue: Get killed and press F1.

**Expected Results:**
First issue: I would expect it to say something like "Sent just now", "sent 1 minute ago" and so on.
Second issue: I would expect to still be able to see all texts sent between me and another person instead of the ones I have sent.
Third issue: I would expect you to be unable to use the phone while you're killed and technically unconscious.

**Actual Results:**
First issue: Currently when you receive a text message the phone will start out with saying "sent 1 hour ago" and counting up from that. It would be much better if it started with "Sent just now" like a real phone and then it counts up in minutes, hours, days and at the end dates.
Second issue: When you receive a text from someone and you re-log, it only shows you texts that you have sent.
Third issue: When you're unconscious (actually dead) you're still able to use your phone, which a lot of people abuse spamming us EMS with calls about them "being dead".

## More Info
**Game Resolution:**
3440x1440 (21:9)

**Notes:**
I feel like a better system for the phone would be so that while you're dead you're unable to use your phone, if there is no EMS on the distress signals could be forwarded to the cops even though it is not their job. I am not a big fan of that solution since it's not the cops job to help civilians up, but it could be a solution.

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
