### ISSUE TITLE
Suggestion: Garage at House usable.

### ISSUE THREAD

**Issue by GrandAct** [InZidiuZ/LegacyRP-feedback#118]
**Suggester:** Unique#3327
 
**Summary:**
Allow players to be able to store and spawn their bought vehicles at the garage (if applicable) at their bought/rented homes.
 
**Reason:**
This adds more depth to the roleplaying experience, at the end of a session I can drive to my house, store my car, walk inside and log off.
 
**Economy:**
No, pricing structure should stay the same.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. The housing system is still very much in development and further changes will come to make it better. We plan to add garages to appropriate houses that would work similar to the public garages.

**Nateღ**
_Legacy RP Staff & Developer_
