### ISSUE TITLE
Suggestion: Dice game

### ISSUE THREAD

**Issue by stiabjoh** [InZidiuZ/LegacyRP-feedback#119]
Suggester: Freeman#4747

Summary:
Allow players to play a game of dice, where you can choose between how many dices and that number you want to go to. It would be displayed as the same way as /me is displayed. Maybe also make a bet/challenge function where you challenge opponent and winner takes the money. 

Reason:
This adds more depth to the roleplaying experience and who doesnt love some gambling. 

Economy:
Should be able to buy the dice at the general store for low cost.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. More ways to games and gambling between players sounds like a good idea. We'll look into ways to do this.

**Nateღ**
_Legacy RP Staff & Developer_
