### ISSUE TITLE
Exclusive Audi RS6 bugs.

### ISSUE THREAD

**Issue by SuckHotFarts** [InZidiuZ/LegacyRP-feedback#121]
**Reporter:**
Who is reporting this? Please include discord name.

SuckHotFarts#0631

**Summary:**
Write a short summary of what you're experiencing.

Two bugs I have noticed with this car. First issue; Transmission upgrade to Sports will not save, $15000 a pop and I've done it three times. This time I applied it, drove out and drove right back in, immediately have to purchase again. I have tried buying it, garaging my vehicle and checking again to no luck. 

Second issue: It's a 4 door but it will not let more than two people in the vehicle. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

1. Get the Audi RS6 and try to apply racing transmission, it will apply and then delete itself immediately. Wasting the cash and not giving the upgrade. 

2. Have two people in the vehicle and try to have someone enter the vehicle using the back doors. Won't work.

**Expected Results:**
What are the expected results?

1. Upgrade will save after garaging vehicle.

2.  Up to 4 or 5 people will be able to enter the vehicle.

**Actual Results:**
What are the actual results?

1. Upgrade will not save no matter the circumstance.

2. Only two people may enter a 4 door vehicle.

## More Info

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

![image](https://user-images.githubusercontent.com/49770887/56400502-33dc5a80-6222-11e9-80a5-c221deab18b8.png)

**Game Resolution:**
What is your game's resolution?

2560x1440

**Player Data:**
Write /info whilst ingame and provide the information you're given.

SYSTEM: [EssentialMode] Version: 6.1.0
SYSTEM: [EssentialMode] Commands loaded: 43

**Notes:**
I think it should be an AWD vehicle not rear wheel but I don't know if that's able to be implemented lol! Thanks for the dope server!

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue. The handling for all vehicles is being redone and should be a huge improvement over the exclusives from the previous version.

**Nateღ**
*Legacy RP Staff & Developer*
