### ISSUE TITLE
car not coming out

### ISSUE THREAD

**Issue by snovle** [InZidiuZ/LegacyRP-feedback#122]
Every time I pay 1k to retrieve my exclusive Bugatti, it doesn't come out and it crashes my game immediately

**Comment by N8teZero** [comment]
Hey,

I've seen bugattis driving around recently, so I assume this issue was resolved. It was likely a client-side cache issue, so if you continue to crash from loading the vehicle, be sure to clear cache.

**Nateღ**
_Legacy RP Staff & Developer_
