### ISSUE TITLE
Joe Crow #0211

### ISSUE THREAD

**Issue by xandoriax** [InZidiuZ/LegacyRP-feedback#123]
**Suggester:**
Joe Crow #0211
 
**Summary:**
I am suggesting to add a bot for EMS that logs the time played, as it does for PD, i dont know how their bot does it i just heard that they have a bot that logs time played and that will help EMS greatly!
 
**Reason:**
Adding this to EMS will help us see who is active and who is not, we will be able to promote and demote people with less hassle and it will feel like a more proffessional enviroment to be in
 
**Economy:**
None what so ever.

**Comment by N8teZero** [comment]
Hey Joe,

I'll add this to my list as it should be fairly easy to setup as we have it for a few other things already.

Thanks,
Nateღ - LegacyRP Staff & Developer
