### ISSUE TITLE
Vehicles not purchasable at used car dealership

### ISSUE THREAD

**Issue by dragonn-n** [InZidiuZ/LegacyRP-feedback#125]
**Reporter:**
Who is reporting this? Please include discord name.
 dragonnn#0121
**Summary:**
Write a short summary of what you're experiencing.
 I am trying to buy a vehicle off the used car dealership and with money in hand or in the bank the vehicle can't be bought
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
 Go to the used car dealership, with money in hand or in bank and attempt to buy a vehicle.
**Expected Results:**
What are the expected results?
 Vehicle should be purchasable and disappear from the lot and appear in your garage
**Actual Results:**
What are the actual results?
 When clicking E to open the buy menu and you confirm it the vehicle doesn't disappear and doesn't appear in the garage.
## More Info
 
**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
 https://i.imgur.com/cY2kAk8.png
https://i.imgur.com/BZqqnfA.png
https://i.imgur.com/icLsfxW.jpg
https://i.imgur.com/qCGV72B.jpg
https://i.imgur.com/JyDF0lf.png
**Game Resolution:**
What is your game's resolution?
 1920x1080
**Player Data:**
Write /info whilst ingame and provide the information you're given.
 EssentialMode Version 6.1.0
Commands Loaded: 43
**Notes:**
For anything else noteworthy.

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
