### ISSUE TITLE
New House Bug

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/LegacyRP-feedback#128]
Reporter: Blanket - Blanket#1998

Summary: Sold houses to players, later on the players were no longer able to access said houses and the icon to enter the houses was gone and will not reappear.

Steps to Reproduce: Buy a house, then the house entrance is gone. You have no house, ripperoni pepperoni.

Expected Results: Enter the house as is necessary

Actual Results: You can't enter the house, the icon is gone. It's a sad story. :/

**Comment by dragonn-n** [comment]
i'm having this issue, bought a house can't seem to enter it after this restart

**Comment by InZidiuZ** [comment]
This issue has been resolved. The fix will be pushed with the next update.
