### ISSUE TITLE
EMS needs : escort / Take out of vehicle = functions ADDED to EMS menu 

### ISSUE THREAD

**Issue by mystorydank** [InZidiuZ/LegacyRP-feedback#129]
EMS needs to be given the ability to Escort / take out of vehicle 
--- In the EMS menu , F6 function --- EMS MENU  : / Escort / Take out of Vehicle
 Giving EMS the ability to take Patient back to Hospital ( for Roleplay purposes ), assisting patients to their vehicle's during critical injuries . Also having Ability to take the  civilian out of the vehicle and help them when injured. 
-------
If needed maybe EMS can handcuff for medical procedures to hold the patient still. even an medical arrest till police will arrive. (maybe thats too much but , please ESCORT , and take out of vehicle . -- D. Story , Chief of Medicine

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
