### ISSUE TITLE
EMS utilities spawn / vehicle spawn  = Outside Sandy shores Hospital 

### ISSUE THREAD

**Issue by mystorydank** [InZidiuZ/LegacyRP-feedback#130]
Up north near sandy shores , along a very busy highway , and where most of Los santos will commit crime and Roleplay outside of town. It becomes needed to resupply or change vehicle for EMS , it would only require outside use of the facilities , with no helicopter pad. To resupply medkits or even change to an ambulance.  it would be 3 trigger's . opposite side from the Police , near archway at the back door.   
----------
Vehicle Spawn on drive way / medits and bandages at the door / maybe not needed for uniform but can stick it at another door way. Purple trigger's to symbolize EMS only access! 
---------
It is a half way point for outside of town , the GOH and even going from call too call with more functions we could always bring patients back to our main hospital for any surgery .
-------------------
Chief of medicine , D. Story

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
