### ISSUE TITLE
Society fund not visible?

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/LegacyRP-feedback#131]
Reporter: Blanket

Summary: Society funds are gone from bosses now.

Steps to Reproduce: Idk, the funds just arent showing

Expected Results: The society funds should be visible
Actual Results: The society funds are not visible.

**Comment by InZidiuZ** [comment]
@N8teZero

**Comment by N8teZero** [comment]
Had no issues on the test server, but will take a look tonight when I get home. Feel free to take a look if you get time. ;) @InZidiuZ

**Comment by InZidiuZ** [comment]
:) @N8teZero

**Comment by N8teZero** [comment]
Hey,

Resolved

**Nateღ**
_Legacy RP Staff & Developer_
