### ISSUE TITLE
Suggestion : Durgs/Mafia

### ISSUE THREAD

**Issue by WaterTheFire** [InZidiuZ/LegacyRP-feedback#132]
### **Suggester:**
**InGame** - Gudown Mani                   **Discord** - WaterTheFire#8432

### **Summary**:
I have many suggestions. First off - Adding Cocain,Meth and Opium.
Also - the Opium,Meth,Cocain,Black Market and Money washing should be hidden locations not on the map. It should be controlled by NPC's. Also give time for processing the drugs instead of it being instant. Makes it a bit more realistic. Say 1 hour. 

For the Money washing - do the same % cut and give it more time like 1 day or so. All this makes it more interesting and makes it a bit more "wanting to play".

### **Reason**:
All of my above suggestions brings up a new "Mafia" that actually have a decent amount of power in the game.They can figure out the locations - sell the locations. It will feel like they have power and bring up different and more rivalry in the city.
It will bring in more roleplay and alot more fun to play. Gives us an incentive. 

### **Economy**:
It will change the economy by delaying the time of making dirty money but can be a great incentive.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. Further expansions on the illegal market are things we are exploring for future updates on the new framework, including drugs.

**Nateღ**
_Legacy RP Staff & Developer_
