### ISSUE TITLE
Suggestions: some old keybinds back

### ISSUE THREAD

**Issue by Semucat** [InZidiuZ/LegacyRP-feedback#134]
Hi,

Short and simple: I believe the keybound animations for B, G and X should still be in the game, as those are some you use really frequent in RP and interaction.

Thank you,
love you,
Semu

**Comment by ShelbsShelbs** [comment]
I agree with X and B for sure, and would love to have G as crossed arms still. When cops tell someone to put their hands up now, they will only be able to *IF* they binded that animation to one of their F buttons. X and B are not being used for anything currently as far as I can tell but were very frequently used as Semu said.

**Comment by InZidiuZ** [comment]
We could add the ability to bind animations to said keys (X, B and G) as long as we don't decide to use them for something else.

**Comment by Semucat** [comment]
> We could add the ability to bind animations to said keys (X, B and G) as long as we don't decide to use them for something else.

Would probably be enough, as I assume if a new player joins he wouldn't really miss the ability but would have the chance to get used to it nevertheless.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. We'll look at having those keys bindable in the same way the 'F' keys are.

**Nateღ**
_Legacy RP Staff & Developer_
