### ISSUE TITLE
Suggestion: Emote cancel.

### ISSUE THREAD

**Issue by SuckHotFarts** [InZidiuZ/LegacyRP-feedback#135]
Suggester: Who is suggesting this? Please include discord name.

SuckHotFarts#0631

Summary: Write a short summary of what your suggestion is about.

The ability to cancel emotes with: 
/e c
/e cancel
/e end

Reason: Why would your suggestion be a good addition to Legacy?

Me personally I prefer text inputs to keybinds but having both options is great as well I think. Can't hurt to have more options!

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will? 

No.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. More command options for animations will be tested.

**Nateღ**
_Legacy RP Staff & Developer_
