### ISSUE TITLE
Unable to emote with a pet out

### ISSUE THREAD

**Issue by LadyH0pe** [InZidiuZ/LegacyRP-feedback#136]
**Reporter:** 
Lady Hope#0541
 
**Summary:**
- When you do /Pets you then no longer use an Emote bound by one of the new F1 muscles. It resets the hotkeys 
 
**Steps to Reproduce:**
Do /Pets , call a pet then try emote and then do /e and your emotes are reset 
 
**Expected Results:**
You are meant to be able to emote
 
**Actual Results:**
You can no longer emote with a pet out
 
## More Info
 
**Player Data:**
Version 6.1.0
Commands Loaded 41
 
**Notes:**
Females also cant use emotes:
- Checklist 
- Parking Attendant
- Paparazzi

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
