### ISSUE TITLE
Suggestion: Remap old keys that are overlapping

### ISSUE THREAD

**Issue by lambertd5512** [InZidiuZ/LegacyRP-feedback#137]
**Suggester:**
Ruby aka Rahzel#6296
 
**Summary:**
I don't see any option in the settings to remap the hotkeys for K (engine toggle) and P (P causes the phone to close while typing), so I think they should be remapped.
 
**Reason:**
I think it would be a good idea because the overlapping hotkeys can be a bit frustrating when trying to access your inventory in your car or typing a message and your phone disappearing and reappearing any time you press P
 
**Economy:**
I don't think it will have any effect on the economy because it was implemented previously.

**Comment by InZidiuZ** [comment]
K no longer toggles engine, and was replaced with /engine. The issue with the phone was also resolved a few days ago.
