### ISSUE TITLE
Game crashes when try to spawn a owned vehicle

### ISSUE THREAD

**Issue by jakeeven21** [InZidiuZ/LegacyRP-feedback#139]
[CfxCrashDump_2019_04_27_23_22_16.zip](https://github.com/InZidiuZ/LegacyRP-feedback/files/3124438/CfxCrashDump_2019_04_27_23_22_16.zip)

I bought a bugatti and now everytime i go to spawn the vehicle, my game crashes and i tried restarting computer and switching servers.
thanks jake

**Comment by N8teZero** [comment]
Hey,

This is likely an issue due to cache, try clearing your cache and see if the issue persists. I've seen people driving their bugatti, so I don't think it's an issue with the vehicle specifically.

**Nateღ**
_Legacy RP Staff & Developer_
