### ISSUE TITLE
EMS alerts doesn't work

### ISSUE THREAD

**Issue by Manyfeso** [InZidiuZ/LegacyRP-feedback#14]
**Suggester:**
Manyfeso, Manyfeso#8819

**Summary:**
EMS doesn't receive calls from unconscious people. We recieve them only from living people.

**Comment by InZidiuZ** [comment]
This issue have been resolved. If the problem persists, please reopen the issue. For future reports, please fill out the entire template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
