### ISSUE TITLE
Game crashes when players attempt to spawn bugatti

### ISSUE THREAD

**Issue by xxxanxiety** [InZidiuZ/LegacyRP-feedback#140]
**Spawning bugatti crashes game**

I have recieved reports from 3 different players that spawning the premium vehicle "Bugatti" crashes their game.

**Comment by N8teZero** [comment]
This is likely an issue due to cache, try clearing your cache and see if the issue persists. I've seen people driving their bugatti, so I don't think it's an issue with the vehicle specifically.

**Nateღ**
_Legacy RP Staff & Developer_
