### ISSUE TITLE
House issues (cont.)

### ISSUE THREAD

**Issue by BlankeyBoi** [InZidiuZ/LegacyRP-feedback#141]
Reporter: Blankety Boyo

Summary: Players are still getting house problems where they are unable to see their homes (the entry text, 'Press 'E' to Enter X home'.  It typically happens to a handful of players after a server restart.

Steps to Reproduce: Go to their house, they don't see it.

Expected Results: Enter the home

Actual Results: Can't see the entry text for their house.

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
