### ISSUE TITLE
EMS BLIPS / Tracker for any EMS on Duty!

### ISSUE THREAD

**Issue by mystorydank** [InZidiuZ/LegacyRP-feedback#143]
MyStOrYdAnK - mystorydank - Z-902 D. Story

Would it be possible to have blips on the map of other EMS? to let other EMS know if someone is in their server if they don't go into dispatch. Maybe available for EMS the same as police have.

It could help EMS understand if anyone is online In their server. Also could help with knowing where they are located when entering a server! EMS is hard too keep track of when any can go on any server and no way to know how many there is.

I believe it could help the server with the EMS , bringing them more to be able to enjoy the job and even track when someone might have an EMS position and is fired , because some people might not take it upon them selves to ask to change their job.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. I think it would be good for PD and EMS to both have blips(different colors) so PD can see if EMS are nearby and vice versa. This would allow emergency services to work better along side each other.

**Nateღ**
_Legacy RP Staff & Developer_
