### ISSUE TITLE
Bug Report: Misplaced Store icon on map

### ISSUE THREAD

**Issue by RickyScurvy** [InZidiuZ/LegacyRP-feedback#144]
*Reporter:**
RickyScurvy 
 
**Summary:**
There is a store that shows on my map but leads to nothing. 
 
**Steps to Reproduce:**
Not known, it is visible with every login. 
 
## More Info
![20190429165256_1](https://user-images.githubusercontent.com/50123542/56934168-e96ba100-6a9f-11e9-950d-8913b17325ef.jpg)
![20190429165223_1](https://user-images.githubusercontent.com/50123542/56934169-eb356480-6a9f-11e9-81b3-7412ab48e2a5.jpg)
![20190429164426_1](https://user-images.githubusercontent.com/50123542/56934170-ec669180-6a9f-11e9-919d-7789369230f1.jpg)

**Comment by N8teZero** [comment]
Hey RickyScurvy,

I've fixed this in the next update, as well as made Hardware stores have a unique icon to quickly find them from the normal shops.

Thanks,
Nateღ - LegacyRP Staff & Developer
