### ISSUE TITLE
Suggestion List. After playing on OP-framework 

### ISSUE THREAD

**Issue by PhizioN** [InZidiuZ/LegacyRP-feedback#145]
**Suggester:**
Who is suggesting this? Please include discord name.
PhizioN#4462 

**Summary:**
I have several suggestions after traveling to different cities.

1. Make it harder to get marijuana (even harder than it currently is on the OP-framework.) I propose that you add a few steps to the process. Instead of currently having full access to fully grown cannabis plants, we would have to find a hidden vendor to purchase the seeds. After purchasing the seeds we would have to find a hidden area with nutrient rich soil, to plant the seeds, and from that point, we have to care for the plant in such a way that we could mess it up if we select the wrong option. For example: upon planting the first seed, a question would pop up saying "this soil is starting to look weak" then there would be a few options to choose from, a) water the plant, b) toss and turn the soil, c) trim the plant, and obviously for that option they would have to select b, or the plant would die. If they successfully complete all the stages, they end up with buds, that they THEN have to process. after they finally process, it is ready to be sold to people.

2. Add more drugs to the game. For example: have a market that has cocaine, marijuana, meth, and or heroine. Maybe demote marijuana to something that is only a fine-able offense by the PD and have the PD's concern shift more towards the harder drugs.

3. Pertaining to second suggestion, possibly only have the harder drugs give dirty money, and have marijuana just give regular money since it would be the least, hardest drug out of the other options, and also more common, which is why locals would give clean money for it.

4. Increase the amount of money it would cost to impound your car so that people are FORCED to utilize the mechanic and interact with someone! I noticed in a different city, it was an extremely ridiculous amount of money to impound your car once you lost in water, or flipped it, etc. It was around 5K to do that. The car that I purchased cost about 300 dollars. So there would be no point to impound it, it would be far cheaper, and more fun, to wait for a tow-truck driver to show up and have a chat with you, charging you FAR LESS money, and most importantly RP-ing. It's almost too easy to be independent on legacy, where as I felt when I went to this other city, it forced me to have to play out a lot more situations that I could've easily avoided by paying the money for the repair kit, and or the 1000$ to retrieve my car.

5. Pertaining to the #4 suggestion, completely reduce the amount of work that repair kits do on your car. Maybe replace the current /repair command's abilities with what a repair kit can do, so that we are FORCED to go up to a mechanic to fix our vehicles.

6. Add the ability to see your radar on foot! Just because we aren't in a vehicle, doesn't mean we cannot access google maps on our phones, with the "on-foot" option, so we should be able to see where we are going without having to open up the map every time.

7. Add in the tow-truck drivers as a job

8. Add in lock-picks in order to access locked vehicles. These can be found either in the salvage diver job, as a low drop rate, and bought and sold to the secret vendor where you get the items needed to further pursue black-market endeavors. 

**Reason:**
Why would your suggestion be a good addition to Legacy?

I believe all suggestions I proposed would force people towards the very mission, we all are on while in this great city, which is to interact with others. Not only would this greatly increase the number of rp situations people get their selves into, but it would make things more challenging, and fun. Things are fun when you have to work hard for them.

**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?

It certainly would have a good effect on the economy, especially in the sense that mechanics will be making more money, and there will be more flow of money traveling through such as tips for service, and having more things to buy and spend on, such as the drugs, lock picks, seeds, and everything else mentioned.

**Comment by SuckHotFarts** [comment]
I agree with all of this.

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, we will archive this for later use. Many of the suggestions have already been, either fully, or partially implemented already.

**InZidiuZ**
Legacy RP Developer
