### ISSUE TITLE
Suggestion: Lawyers 

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/LegacyRP-feedback#147]
**Suggester:**
John Pilgrim Agent_Grunt#0344

**Summary:**
Having the ability to do /lawyer to announce lawyers are in town. 

**Reason:**
so Lawyers can let everyone know they are online and willing to help.

**Economy:**
only effect is the lawyers will make money.

**Comment by ExpDev07** [comment]
Very good suggestion!

**Comment by N8teZero** [comment]
Hey,

I've added this command into the next push. It will be /lawyer and available to only lawyers.

**Nateღ**
_Legacy RP Staff & Developer_
