### ISSUE TITLE
Suggestion/Issue Mechanic

### ISSUE THREAD

**Issue by lDEADEYEI** [InZidiuZ/LegacyRP-feedback#148]
**Suggester:** DEADEYE/William McGuire/Justin Case

**Summary:** I am going to list these in order of importance. (IMO)
1. Make Flatbeds and Tow Truck purchasable in dealership. (only for mechanics if possible)
2. Ability to attach vehicles tow truck similar to flatbed.
3.  Ability for mechanics to run License plates.

**Reasons:**
1-1. Currently mechanics can not lock their work vehicles as they do not own them. This results in players stealing our work vehicles consistently.
1-2. Having the ability to purchase our own work vehicle will allow mechanics to customize said vehicle. This will allow each mechanic to define their-selves visually and gives incentive to RP more often with their work vehicle. (I.E. Actually tow more vehicles as opposed to just "impounding" to make them disappear.
2. Currently the Tow Truck is unusable, you can not attach a vehicle to it.
3-1. This will allow mechanics to identify abandoned/stolen vehicles taking up parking spots etc...
3-2. It will also allow mechanics to identify the owners of abandoned vehicles to either contact them and/or bill them for abandoning their vehicles.

**Economy:** 
I do not think this will have any impact on the economy ans it doesn't deal with money, aside from purchasing the Flatbed and 2 Tow Trucks.

**Comment by N8teZero** [comment]
Hey,

Great suggestions. I am archiving this to add to our development list for OP-Framework as that is where we are focusing currently. This will have many improvements over the current system. I think these ideas will greatly improve the mechanic job and interactions. 

**Nateღ**
_Legacy RP Staff & Developer_
