### ISSUE TITLE
Bug: Billing for Lawyers

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/LegacyRP-feedback#149]
**Reporter:**
Agent_Grunt#0344
 
**Summary:**
The billing feature for Lawyers currently doesn't work.
 
**Steps to Reproduce:**
Press F6 to bring the lawyer menu up. press Enter on billing. type in the amount. press submit. nothing happens. 
 
**Expected Results:**
Our Clients being billed for our services. 
 
**Actual Results:**
nothing happens.

**Comment by N8teZero** [comment]
Hey,

I will test this out, but to verify you are standing next to the client you are trying to invoice? It should work like the invoices for the other businesses, but will check to be sure.

**Nateღ**
_Legacy RP Staff & Developer_

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
