### ISSUE TITLE
Garage suggestion

### ISSUE THREAD

**Issue by GeorgeLUA** [InZidiuZ/LegacyRP-feedback#15]
**Suggester:**
Who is suggesting this? Please include discord name.
George
 
**Summary:**
Write a short summary of what your suggestion is about.
be able to return your vehicle if it gets inpounded
 
**Reason:**
Why would your suggestion be a good addition to Legacy?
would make it better
 
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
No

**Comment by InZidiuZ** [comment]
Suggestion approved.
