### ISSUE TITLE
Suggestion: Favorite Phone add 

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/LegacyRP-feedback#150]
**Suggester:**
agent_grunt#0344
 
**Summary:**
Just like how the Police, EMS, Taxi, and mechanics have a favorite tab on the phone i think the lawyers should have the same thing.
 
**Reason:**
It would notify the lawyers that is in the city that they have a client on stand-by and so the PD or client doesn't have to spam twitter asking about a lawyer if its on your phone already. 
 
**Economy:**
None

**Comment by N8teZero** [comment]
Hey,

I've added the lawyer contact to the phones in the next update.

**Nateღ**
_Legacy RP Staff & Developer_
