### ISSUE TITLE
Koenigsegg cars to Exclusive shop

### ISSUE THREAD

**Issue by BestDriverEU** [InZidiuZ/LegacyRP-feedback#151]
**Suggester:**
Best Driver EU

**Summary:**
Adding a or more Koenigsegg vehicles to the floor 2-3(both possibly) in the Exclusive car shop

**Reason:**
Koenigsegg is a top super car in the World and is very beutyful and fitting for the server

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, we'll look into adding more variety to the dealerships. They will work very different to the current dealerships.

**Nateღ**
*Legacy RP Staff & Developer*
