### ISSUE TITLE
Suggestion: New Features for Contacts in Phones

### ISSUE THREAD

**Issue by ImSilvur** [InZidiuZ/LegacyRP-feedback#152]
It would be a lot more convenient if you could do a few different things with the contacts on your phone.
-Add someone as a contact from a message
-Have the ability to delete contacts
-Have the ability to edit contacts
Without these, it makes adding contacts a hassle and incentivizes people to communicate and use their phone's less. At this point, if you accidentally mess up a contact, you have to make a new one, and add something else to the name so that you know it's the correct contact, not the one you messed up and can't delete.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. Many phone improvements are planned in the new framework, so these good ideas are documented.

**Nateღ**
_Legacy RP Staff & Developer_
