### ISSUE TITLE
Suggestion: Icon for courthouse

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/LegacyRP-feedback#153]
**Suggester:**
Agent_Grunt#0344
 
**Summary:**
A marker/icon on the map for the courthouse.
 
**Reason:**
So the clients of the lawyers would know where to go.
 
**Economy:**
None

**Comment by N8teZero** [comment]
Hey,

Added blip for courthouse in the next update. 

**Nateღ**
_Legacy RP Staff & Developer_
