### ISSUE TITLE
Suggestion: Bar Id Cards for Lawyers.

### ISSUE THREAD

**Issue by AgentGrunt** [InZidiuZ/LegacyRP-feedback#154]
**Suggester:**
Agent_Grunt#0344
 
**Summary:**
An ID for the lawyers to show the police to prove they are lawyers.
 
**Reason:**
So the police doesn't have to search us to find out if we are lawyers or not.
 
**Economy:**
none

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this no longer stands.

**InZidiuZ**
Legacy RP Developer
