### ISSUE TITLE
One global cooldown for the stores/banks

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#155]
#### Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
One global cooldown to cover all Rob-able store/bank.

#### Reason: Why would your suggestion be a good addition to Legacy?
Police should be able to response to the robberies.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
It will effect the economy in a good way, as it would be harder to rob a store.

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**InZidiuZ**
Legacy RP Developer
