### ISSUE TITLE
Robbing houses

### ISSUE THREAD

**Issue by Jif14** [InZidiuZ/LegacyRP-feedback#156]
Discord: Jif14#6332

I think it would be cool to be able to rob houses and you would have to have a lockpick or some item to be able to get into a house, and sometimes but not very often npcs will have guns and attack you if you are detected. And cops would be alerted if an npc in the houses sees you or some kind of alarm is triggered.

I think it would benefit the server by giving more options to make money for players and it would add realism for people role-playing as criminals.

Depending on the money you get for robbing a house it could possibly effect the economy but that's all up to how much you get per robbery.

**Comment by ExpDev07** [comment]
Thing is, apartments should be a place where people know their items are 100% safe unless law enforcement has a warrant.

**Comment by Jif14** [comment]
> Thing is, apartments should be a place where people know their items are 100% safe unless law enforcement has a warrant.

NPC Houses not player houses lmao

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this is a planned feature further down the timeline.

**Nateღ**
*Legacy RP Staff & Developer*
