### ISSUE TITLE
House doors not working 

### ISSUE THREAD

**Issue by CoLewGaming** [InZidiuZ/LegacyRP-feedback#157]
**Reporter:**
Colew #4449

**Summary:**
Bought a house and couldn't get into it so I decided to help a few buddies out and bought them houses and none of them can get in. A total of around 10 homes have never been accessed.
Not sure what to do because it's been roughly 5 days 

**Steps to Reproduce:**
Go to the house that is bought and attempt to access it. 

**Expected Results:**
To enter the house by pressing E

**Actual Results:**
You can not get in. 

## More Info

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920x1080

**Notes:**
Was told when buying the house that I might experience a scuff or two however, I have experienced only a scuff. Never once have I been in my house. Likewise with all of my friends.

**Comment by N8teZero** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**Nateღ**
*Legacy RP Staff & Developer*
