### ISSUE TITLE
Dance Animations

### ISSUE THREAD

**Issue by ShelbsShelbs** [InZidiuZ/LegacyRP-feedback#158]
Suggester: Who is suggesting this? Please include discord name.
Shelbs#9300

Summary: Write a short summary of what your suggestion is about.
Adding dance/stripper animations back. Currently, I have no reason for hiring dancers as they cannot actually dance at the Unicorn.

Reason: Why would your suggestion be a good addition to Legacy?
We use to have the ability to dance and it would add more RP to the Vanilla Unicorn again.

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Gives players another area to use their money, as well as revolves money through the city.

**Comment by InZidiuZ** [comment]
Hey,

This has been added with OP-FW.

**InZidiuZ**
Legacy RP Developer
