### ISSUE TITLE
Suggestion Bank robbery

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#16]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Make a cooldown for bank robbery, so you cant rob 3 different banks withing 10 mins.
Also when robber leave the place, pd should get a notification about that the robbery got canceled.

#### Reason: Why would your suggestion be a good addition to Legacy?
Prevent people to start multiple bank robberies in the same time and ruin the economy.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Yes, it would keep the economy healthy in way, which avoids people to start multiple bank robberies

**Comment by InZidiuZ** [comment]
Suggestion approved. Bank robberies will now have a 10 minute cooldown between each other. However, as the robberies are split into multiple steps, a "canceled" notification wouldn't be very useful nor accurate.
