### ISSUE TITLE
Car's Scuffed

### ISSUE THREAD

**Issue by CoLewGaming** [InZidiuZ/LegacyRP-feedback#160]
**Reporter:**
Colew #4449

**Summary:**
The car's not working when trying to get in after going all the way up north for chicken runs. 

**Steps to Reproduce:**
Fill up the gas, use a repair kit or anything that requires to modify the car's current state.

**Expected Results:**
To fill up the gas/ finish a chicken run and get into the car with the squad.

**Actual Results:**
Fill up gas/ finish chicken run and the car door opens but character freezes midway of entering car. 

## More Info

**Screenshots:**
I have them however it is still currently recording if needed I will get it. 

**Game Resolution:**
1920x1080

**Notes:**
Doesn't happen 100% of the time however, 8/10 times the car will get scuffed which usually ends with a $1000 retrieval cost and a ticket
for a stollen car.

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**InZidiuZ**
Legacy RP Developer
