### ISSUE TITLE
Police Limits for Robberies

### ISSUE THREAD

**Issue by Stanglife0419** [InZidiuZ/LegacyRP-feedback#161]
Now that limits for committing robberies have been established (4 for stores, 7 for banks), I think it's time for police to be limited on their response as well. Multiple times I have watched store robberies where the police response to a store robbery has been 8+ cops with air support, and even SWAT on the last one. There is no way for any quality RP to come from this, as it takes away any motivation for negotiation or back and forth. It becomes more about the police "winning" the encounter than having a quality engagement. I believe the limits for robberies should be the same for the police as for the criminals: 4 for stores, 7 for robberies.

**Comment by ExpDev07** [comment]
Hey! This GitHub is more for submitting bug reports and suggestions related to the technical side of the server. Your suggestion is more looking for a rule change, which would get more debate and attention from the rest of the community besides of our developers if you post it at our forums: https://legacyroleplay.online/c/suggestions/vehicles.

**Thanks for understanding,**
M. Truckster
Community Manager

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**InZidiuZ**
Legacy RP Developer
