### ISSUE TITLE
Street Blazer can not be upgraded

### ISSUE THREAD

**Issue by BestDriverEU** [InZidiuZ/LegacyRP-feedback#162]
**Suggester:**
Michel McRay  - Best Driver EU#2105

**Summary:**
the Street Blazer can not be upgraded or even chnage color on it, in GTA Online and SP it have alot of features to be made on

**Reason:**
The Street Blazer is cool and have its potential in its upgrades

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this will (?) no longer be an issue.

**InZidiuZ**
Legacy RP Developer
