### ISSUE TITLE
Tailor outfit impersonats cop

### ISSUE THREAD

**Issue by nealj121** [InZidiuZ/LegacyRP-feedback#163]
I had a lengthy conversation I was impersonating a cop with the tailor outfit... I think that needs an update SO I DON'T GET ARRESTED.

I have a clip from plays recorded of that fun talk of this... If I can get it on here.

Edit. Please change the work vehicle too. Something more of a work vehicle would be great.

Edit https://plays.tv/s/MDCZ9ggaQQJe me almost being arrested doing my job with the uniform GIVEN to me

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**InZidiuZ**
Legacy RP Developer
