### ISSUE TITLE
Update Exclusive Dealership

### ISSUE THREAD

**Issue by Burnzalot** [InZidiuZ/LegacyRP-feedback#164]
**Suggester:**
BurnZalot/Jon Juugs
**Summary:**
I'd like to see more cars or inventory rotations at the exlcusive dealership, And cars at the regular dealership have realistic top speeds. Id hate to spend 1.5mill just to go 120. Also a way to resell or maybe have certain people be able to sell the "used"exclusive vehicles as a Car salesman job/Custom Tuner(would create more opportunity for RP) 
https://www.gta5-mods.com/vehicles/2013-lamborghini-gallardo-lp560-4-lapd
https://www.gta5-mods.com/vehicles/lamborghini-huracan-super-trofeo-add-on-hq-1-0
https://www.gta5-mods.com/vehicles/lamborghini-countach-qv-add-on-tuning-dover5
https://www.gta5-mods.com/vehicles/porsche-911-993-rwb-rotana-93-add-on-replace
Just a few cars for ideas(would love a lambo in dealer)
**Reason:**
Why would your suggestion be a good addition to Legacy?
It would provide more realism, more options for car lovers, as well as more Roleplay options
**Economy:**
It would add another Serious RP role as well as...give mechanics another duty/job option?

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, the exclusive dealership will be changed up quite a bit, so will close this.

**InZidiuZ**
Legacy RP Developer
