### ISSUE TITLE
EMS Helicopter's are unusable.

### ISSUE THREAD

**Issue by Cironite** [InZidiuZ/LegacyRP-feedback#166]
Reporter: A. Ivanov (Ciros#2426)

Summary: EMS Helicopter's spawn locked and cannot unlock them.

Steps to Reproduce: Spawn the helicopter

Expected Results: Being able to unlock the helicopter.

Actual Results: Helicopter unlockable/lockpickable, message box says Vehicle not found.

**Comment by Pieparker** [comment]
As a workaround... if there's a mechanic on the server, they can bust the door open for you for free. Alternatively, you can take a lockpick!

Not ideal though, I get that.

**Comment by InZidiuZ** [comment]
Hey,

With OP-FW releasing soon, this will no longer be an issue.

**InZidiuZ**
Legacy RP Developer
