### ISSUE TITLE
Suggestion Paleto PD station

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#17]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192
Summary: Write a short summary of what your suggestion is about.
Added Paleto PD station.
Reason: Why would your suggestion be a good addition to Legacy?
Since its handy incase of situation happing around paleto.

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope.

**Comment by InZidiuZ** [comment]
Suggestion approved.
