### ISSUE TITLE
Suggestion PD Sherif Department

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#18]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
https://forum.fivem.net/t/release-map-sandy-shores-police-station-upgrade/46161
Add some extra feature for Sherif department.

Reason: Why would your suggestion be a good addition to Legacy?
Makes PD look more prof. and more interesting for new and old players

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope.

**Comment by InZidiuZ** [comment]
This YMAP is a little too "messy" and unrealistic for our standards. (According to my OCD) I suspect it would also have quite some impact on performance, considering this is a YMAP. Suggestion disapproved.
