### ISSUE TITLE
Suggestion Add ATM to PD station

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#19]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
So PD member doesnt have to run to the nearest bank to get enough for a car.

Reason: Why would your suggestion be a good addition to Legacy?
PD will be able to respond quicker since they are forced to run to the nearest bank.

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope.

**Comment by InZidiuZ** [comment]
PD cars are supposed to be a more "permanent" thing, and you shouldn't require running to the bank whenever you're about to patrol. Also, funds for vehicles are supposed to be provided by the chief and other higher ups. Therefore, I deem this suggestion unnecessary. Suggestion disapproved.
