### ISSUE TITLE
PD vehicle storage

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#2]
- What happens? (please give a detailed explanation)
When you upgrade your pd car and storage, then take it out again. It removes the upgrades.
- What did you do to cause this?
Upgrade and then storage it
- Has it always been like this?
nope
- What server version did this happen on?
6.0
- Please include a screenshot of your F8 console

**Comment by InZidiuZ** [comment]
This issue have been resolved. If the problem persists, please reopen the issue. For future reports, please use the correct template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
