### ISSUE TITLE
[Suggestion] Allow dirtbikes to change position in air

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/LegacyRP-feedback#20]
**Suggester:**
Nate
 
**Summary:**
Currently, all vehicles are not able to control direction/tilt while airborne. I think that dirbikes should be able to so they can do sick stunts. This includes the Sanchez, Sanchez Sport, and Manchez(maybe others, idk). 
 
**Reason:**
Backflips
 
**Economy:**
Will have no effect on the economy.

**Comment by InZidiuZ** [comment]
Suggestion approved. :)
