### ISSUE TITLE
Unicorn money wash

### ISSUE THREAD

**Issue by GeorgeLUA** [InZidiuZ/LegacyRP-feedback#21]
**Suggester:**
Who is suggesting this? Please include discord name.
 George
**Summary:**
Write a short summary of what your suggestion is about.
 When i clean money for people it takes way to long for me to get it back clean and i run out of money very fast
**Reason:**
Why would your suggestion be a good addition to Legacy?
 It would make better/more rp for the unicorn aswell as people don't have to wait so long to get their money washed 
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
It might as this will mean they will get cleaned money faster

**Comment by InZidiuZ** [comment]
Suggestion approved. Money washes now go through every day at 8AM and 8PM. (CET)
