### ISSUE TITLE
Can’t visit people in jail without getting stuck

### ISSUE THREAD

**Issue by ExpDev07** [InZidiuZ/LegacyRP-feedback#22]
**Reporter:**
shdw (https://legacyroleplay.online/u/shdw)
 
**Summary:**
So I was going to wait for my friend to get out of jail since we both got caught but I got away. But when I entered the jail and was about to go back I couldn’t get out, instead of going out i went into jail. But when I pressed “Boiling broke” it told me I had no keys for it. Which is a huge bug which needs to be fixed asap.
 
**Steps to Reproduce:**
- Visit jail
- Try and get out
- Press  “Boiling broke” 
 
**Expected Results:**
Get out of the jail.
 
**Actual Results:**
Gets stuck in jail.
 
## More Info
 
**Screenshots:**
https://legacyroleplay.online/uploads/default/original/1X/fdb4d486f2805d7a611dccff05e346b4511ef487.jpeg
 
**Game Resolution:**
Not provided.
 
**Player Data:**
Not provided.
 
**Notes:**
See report here: https://legacyroleplay.online/t/cant-visit-people-in-jail-without-getting-stuck/446.

**Comment by InZidiuZ** [comment]
This issue have been resolved. If the problem persists, please reopen the issue. For future reports, please use the correct template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
