### ISSUE TITLE
More property which u can rent and buy .

### ISSUE THREAD

**Issue by Boblishky** [InZidiuZ/LegacyRP-feedback#23]
Suggester: Boblishky . 
Summary: I think it would a nice edition to the server also there isnt a huge amount of houses in the town or outside the main city . 
Reason: This will give the players the freedom to live in other places and be able to RP in different places because the city gets boring at times. 
Economy: If will give the players more courage to grind for money depending on the prizes .

**Comment by InZidiuZ** [comment]
A better housing-system is being planned. Not sure how far away it is though, as it will surely take some time before it's properly planned out & finished. The suggestion is appreciated!

**Comment by Boblishky** [comment]
ok mate

**Comment by InZidiuZ** [comment]
Such a system has now been implemented. All houses up in Paleto Bay are now buyable & more areas will be added in the future. It is still in an alpha-state & is currently missing a few features such as inviting players to your house and most things for real estate agents, although that'll come in the future! :)
