### ISSUE TITLE
Bug: Wheel Chair

### ISSUE THREAD

**Issue by Vexzarkov** [InZidiuZ/LegacyRP-feedback#24]
**Reporter:**
Vex Zarkov
 
**Summary:**
Bug with the wheel chair allows you to no clip into locked areas such as LSPD 
 
**Steps to Reproduce:**
Get into a wheel chair and drive into a wall or door
 
**Expected Results:**
What are the expected results? You should not be able to clip past it.
 
**Actual Results:**
What are the actual results? You clip past

**Comment by InZidiuZ** [comment]
Due to it being extremely buggy, it is being removed. It may return at some point in the future, if fixed.
