### ISSUE TITLE
Suggestion remove automatic guns from legal gun store

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#25]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
Remove automatic guns from the legal gun store.
such as.
- Assualt shotgun

Reason: Why would your suggestion be a good addition to Legacy?
Assualt shotgun is automatic shotgun which is really powerfull, also before the update it use to be in the illegal gun store

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
It will help keep the economy decent since it would be easier to do robberies with that gun.

**Comment by InZidiuZ** [comment]
Suggestion approved.
