### ISSUE TITLE
Suggestion Swat vehicle

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#26]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add a swat bearcat.
https://www.gta5-mods.com/vehicles/lenco-bearcat-swat-code-3-arch-liberty-more-lights

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the swat team since we are missing one at the moment.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved. The linked vehicle has been added to the server. Do keep in mind though that this vehicle should not be overused.
