### ISSUE TITLE
Suggestion PD prison transport vehicle

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#27]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add a prison transporter
https://www.gta5-mods.com/vehicles/chevy-express-pisoner-transport-unlocked

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the PD with prisoner transport.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved. The linked vehicle has been added to the server.
