### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GeorgeLUA** [InZidiuZ/LegacyRP-feedback#29]
**Suggester:**
Who is suggesting this? Please include discord name.
 George
**Summary:**
Write a short summary of what your suggestion is about.
 That we can lock all the door at unicorn
**Reason:**
Why would your suggestion be a good addition to Legacy?
 It would make more sence to the unicorn
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
no

**Comment by InZidiuZ** [comment]
Suggestion approved.
