### ISSUE TITLE
Wheelchair broken

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#3]
- What happens? (please give a detailed explanation)
Wheelchair is broken in many ways. Someone told me that you could launch your self like a rocket.
- What did you do to cause this?
Spawn and use it
- Has it always been like this?
Nope
- What server version did this happen on?
6.0
- Please include a screenshot of your F8 console

**Comment by InZidiuZ** [comment]
Due to it being extremely buggy, it is being removed. It may return at some point in the future, if fixed.
