### ISSUE TITLE
Bug Legal gun license

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#30]
#### Reporter: Who is reporting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what you're experiencing.
Gun license 1 prices are 2500 but you only pay 250.
same goes for gun license 2 which is 5000 in the menu, but you buy it from 500

#### Steps to Reproduce: Include what steps that are needed in order to reproduce the issue.
You simply go to the gun store and open menu and buy them 90% cheaper.

#### Expected Results: What are the expected results?
You should lose 2500 for the first license

#### Actual Results: What are the actual results?
You only lose 250.

**Comment by InZidiuZ** [comment]
This issue has been resolved. If the problem persists, please reopen the issue.
