### ISSUE TITLE
Suggestion for Unicorn

### ISSUE THREAD

**Issue by GeorgeLUA** [InZidiuZ/LegacyRP-feedback#31]
**Suggester:**
Who is suggesting this? Please include discord name.
 George
**Summary:**
Write a short summary of what your suggestion is about.
 I would like if you added that unicorn also has a menu to buy guns and also sell guns to other people. as both Mafia and Tequilla has it.
**Reason:**
Why would your suggestion be a good addition to Legacy?
 It would make it better for Unicorn aswell as you would not need to add a blackmarket because people can buy from companies
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
No

**Comment by InZidiuZ** [comment]
Suggestion disapproved.
