### ISSUE TITLE
Suggestion Add bulletproof vest to clothing stores

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#32]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add bulletproof vest to clothing stores

#### Reason: Why would your suggestion be a good addition to Legacy?
For better roleplay reasons

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved. Added bulletproof vests & bags to clothing stores.
