### ISSUE TITLE
Suggestion PD gate lockable 

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#33]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Lockable PD gates for the parking lot in the front and back.

#### Reason: Why would your suggestion be a good addition to Legacy?
For better roleplay reasons

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved.
