### ISSUE TITLE
Suggestion PD bike

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#34]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
https://www.gta5-mods.com/vehicles/bmw-r-1200-gs-police-bike-ismadanialeugene

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the PD, so we can follow people on bikes.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Going to put this one aside for a while as I fear the server is being overpopulated with PD vehicles. If you have suggestions to a few that could be removed, feel free to post them here.

**Comment by InZidiuZ** [comment]
Due to [issues with the lightning](https://gyazo.com/0053edaaa5d79e75c40f8553b40006c5), this suggestion will be disapproved.
