### ISSUE TITLE
Suggestion PD vehicle fuel consuming unrealistic

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#35]
#### Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
PD vehicle fuel consuming is too high.

#### Reason: Why would your suggestion be a good addition to Legacy?
PD vehicle uses almost a full tank from PD to paleto which is not realistic. Its a issue for PD since we are forced to refuel quite often.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
PD vehicles and civilian vehicles have the same fuel consumption. The fuel system is supposed to work as a limiter on how far & how long you can drive. Driving from Mission Row to Paleto Bay's sheriff office only takes 36% fuel from a regular PD car, which was how I envisioned the fuel consumption being before making the system. Suggestion disapproved.
