### ISSUE TITLE
Suggestion Driving school speed limits

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#36]
#### Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Driving school needs the speed limits fixed to 35 = in town | 75 = out town

#### Reason: Why would your suggestion be a good addition to Legacy?
So people dont complain about the speedlimits is wrong according to the driving school

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved. The driving school has now been converted to mp/h and speed limits have been corrected.
