### ISSUE TITLE
Suggestion EMS Ambulance

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#37]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
EMS ambulance is way too fast.

#### Reason: Why would your suggestion be a good addition to Legacy?
People starts to realize it and steal ambulance more often.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
I tested on my local server and it now goes to around 100 mp/h with relatively slow acceleration.
