### ISSUE TITLE
Re-Enable /OOC

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/LegacyRP-feedback#38]
**Suggester:**
Nate
 
**Summary:**
I understand why it was removed, but it has not solved the issue. I would rather help new players with basic questions on the spot than play that weird game where I have to explain to them not to use Twitter to talk ooc while not going ooc myself. We shouldn't have to wipe the chat multiple times and send announcements just to eventually kick someone for going ooc in twitter just because someone needs help. It takes a couple seconds to help people out in ooc, but takes much more to enforce no ooc on the server at all.
 
**Economy:**
No Effect

**Comment by InZidiuZ** [comment]
Suggestion approved.
