### ISSUE TITLE
Suggestion Regarding Weapons (Weapons Licenses, Weaponry Available, Custom Weapons Skins, Weapon Sounds, and Weapon Animations)

### ISSUE THREAD

**Issue by BOTMoffatto** [InZidiuZ/LegacyRP-feedback#39]
**Suggester:**
Who is suggesting this? Please include discord name.
BOTMoffatto#0001
**Summary:**
Write a short summary of what your suggestion is about.
My suggestion is to add more weapons and weapon licenses into the game. Examples of this could be a Level 1 and 2 AR Weapons Licence, Where level 1 will allow semi-auto assault rifles and Level 2 will allow fully auto Assault Rifles. Also, there could be a level 3 Weapons License which allows SMG's. The pricing on this can be at the Dev's and Owner's discretion. You could also add more Pistols Like the Heavy Revolver and the AP Pistol. Also adding custom weapon skins will add a little more to the server, making it look more realistic. Also adding animations for pulling out weapons like this (Link: https://www.gta5-mods.com/scripts/pull-out-strap) could be cool adding to the server. Also (Final thing I promise) You could also add some gun sounds to the server, it could add more intensity to gunfire and make it more realistic (Again.).

**Reason:**
Why would your suggestion be a good addition to Legacy?
It would be a good addition to Legacy since it will make the server appear more realistic with the custom weapons skins. Also, it will add a little variety to the server since Police have to actually plan more effectively depending on a situation because now police with AR's have a HUGE advantage over people with Pistols and shotguns. So having the variety in weaponry will make things more balanced and will require the police force to plan different strategies on the fly and while responding, instead of just staying away due to the lack of range of the current weapons.
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
It may, by having people pay more money for weaponry causing them to have not a lot of money and having the government get an increase in funding. Other than, that it won't.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
