### ISSUE TITLE
Gas station blink missing on the map

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#4]
- What happens? (please give a detailed explanation)
Gas station blink missing on the map.
- What did you do to cause this?
Nothing.
- Has it always been like this?
Nope
- What server version did this happen on?
6.0
- Please include a screenshot of your F8 console

**Comment by InZidiuZ** [comment]
This is not an issue. There was intention behind their removal. For future reports, please use the appropriate template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
