### ISSUE TITLE
Map Suggestion 

### ISSUE THREAD

**Issue by Vexzarkov** [InZidiuZ/LegacyRP-feedback#40]
Suggester: Vex Zarkov

Summary: So i feel like sandy needs some love so i seen this pack

Reason: Why would your suggestion be a good addition to Legacy? I feel like this would bring some traffic up north! https://www.gta5-mods.com/maps/sandy-shores-alive

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will? I dont think this will effect it but it may effect where people hang out and give more RP to it!

**Comment by InZidiuZ** [comment]
I fear this would have way too much of an impact on the performance, therefore this suggestion will be disapproved, for now.
