### ISSUE TITLE
Using belt inside vehicle breaks your character

### ISSUE THREAD

**Issue by ExpDev07** [InZidiuZ/LegacyRP-feedback#41]
**Reporter:**
Marius Truckster
 
**Summary:**
When you enter the vehicle and use the hotkey "b" to put the belt on, which is used for the point animation, then your character "breaks" when you leave the car, and you will have to point manually again for it to get fixed. Using "K" to stop the engine also initiates the animation regardless, and you have to use "k" again to fix it.
 
**Steps to Reproduce:**

1. Get inside a car. 
2. Put on belt.
3. Remove belt.
4. Get out of car.
5. Try pointing with a weapon
6. Use "b" to point to fix

------------------

1. Get inside a car.
2. Try toggling engine with "k".
3. You then see your legs go under the car, and you can't get out or do anything until you turn on the engine with "k" again.

**Expected Results:**
For animations not to work when inside a vehicle.
 
**Actual Results:**
Animations happens, and it messes up stuff.
 
## More Info
 
**Screenshots:**
Not applicable.
 
**Game Resolution:**
Not applicable.
 
**Player Data:**
Not applicable.
 
**Notes:**
Not applicable.

**Comment by InZidiuZ** [comment]
This should've been resolved with a recent commit, although I haven't tested it so will wait closing this until it's been confirmed. The fix will be included alongside with 6.0.4c, going live in a few minutes.
