### ISSUE TITLE
Used car dealership

### ISSUE THREAD

**Issue by u-n-M-d** [InZidiuZ/LegacyRP-feedback#42]
**Reporter:**
unMd #0782

**Summary:**
When removing a vehicle that you have placed for sale in the Used car lot, it will be returned to your possesion with no mods.

**Steps to Reproduce:**
Remove your vehicle from sale at the used car dealership.

**Expected Results:**
A previously modified car, now with no mods.

**Actual Results:**
Loss in vehicle modifications.

**Comment by N8teZero** [comment]
Resolved

**Nateღ**
_Legacy RP Staff & Developer_
