### ISSUE TITLE
Suggestion PD Armory

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#43]
#### Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
PD Armory weapons missing for us chiefs to buy it to the armory.
missing the following.
-Carbine Rifle
-SMG
-Teargas

#### Reason: Why would your suggestion be a good addition to Legacy?
PD needs these weapons in order to work out.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
An SMG is already available for purchase (Combat PDW). A custom gun (an M4) will be replacing the carbine rifle in the next update, and will be available for purchase in the armory. Teargas will remain unavailable, for now.
