### ISSUE TITLE
Bug PD boss menu

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#44]
#### Reporter: Who is reporting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what you're experiencing.
PD boss menu to withdraw/deposit society money

#### Steps to Reproduce: Include what steps that are needed in order to reproduce the issue.
You cant withdraw/deposit society money from the location.

#### Expected Results: What are the expected results?
I tried to deposit 300k, but it didnt go in.

#### Actual Results: What are the actual results?
When depositing money it should go in.

**Comment by InZidiuZ** [comment]
This issue has been resolved. If the problem persists, please reopen the issue.
