### ISSUE TITLE
Suggestion SWAT shield

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#45]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add a swat shield
https://www.gta5-mods.com/scripts/shield-mod

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the swat team since they are missing one at the moment.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Invalid suggestion. The attached link is not for FiveM, but GTA 5 singeplayer modding.
