### ISSUE TITLE
Suggestion for Tequilala

### ISSUE THREAD

**Issue by GeorgeLUA** [InZidiuZ/LegacyRP-feedback#46]
**Suggester:**
Who is suggesting this? Please include discord name.
 George
**Summary:**
Write a short summary of what your suggestion is about.
 Make locks on tequilala
**Reason:**
Why would your suggestion be a good addition to Legacy?
 Would be better for the unicorn
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
No

Also id like if you made the ranks like this for tequilala
Bartender
Singer
Security
Supervisor
Manager
Boss

**Comment by InZidiuZ** [comment]
Suggestion(s) approved. This will indeed be great for "the unicorn"!
