### ISSUE TITLE
Bug: Not showing Mechanic online

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/LegacyRP-feedback#48]
**Reporter:**
Nate
 
**Summary:**
Though there is a mechanic online(me), it is showing none. Though this is kind of a blessing because we don't receive texts. But once the other thing is fixed, will need this too.
 
**Screenshot:**
https://puu.sh/CUuxn/3556a120a4.png

**Comment by InZidiuZ** [comment]
This issue has been resolved. If the problem persists, please reopen the issue.
