### ISSUE TITLE
EMS doesn't have salaries

### ISSUE THREAD

**Issue by Manyfeso** [InZidiuZ/LegacyRP-feedback#49]
Reporter: Manyfeso/Manyfeso#8819

Summary: EMS doesn't have money for salaries

Steps to Reproduce: nothing

Expected Results: Money for salaries

Actual Results: EMS doesn't receive money from salaries

**Comment by InZidiuZ** [comment]
This will be resolved with an upcoming update. Salaries will no longer be managed by the EMS higher-ups due to abuse of "government" provided funding.
