### ISSUE TITLE
Requst PD equipment missing 

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#5]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
Add missing PD equipment such as:
-Combat pistol
-Carbine Rifle
-TearGas

Reason: Why would your suggestion be a good addition to Legacy?
Since these are the equipment PD use.

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope.

**Comment by InZidiuZ** [comment]
PD armory has been restocked with new weapons. A slider was also added, for more efficient purchasing.

**Comment by sercanatici** [comment]
PD armory is missing SMG and Carbine Rifle for chiefs to be able to buy.
