### ISSUE TITLE
Suggestion for clothing stores.

### ISSUE THREAD

**Issue by shdwww** [InZidiuZ/LegacyRP-feedback#50]
Suggester: shdw#4340

Summary: I think you should replace the current esx_clotheshop to the one where you can access your saved outfits from the shops.

Reason: I think it would be much easier for people that want to be able to save their outfits without having to buy an apartment just for clothes.

Economy: I really don't think its gonna ruin the economy in anyway, I'm very sure that players are going to enjoy it so they don't have to rent apartments with no money avaible to keep them up.

* Incase you can't find it on the fivem forums feel free to contact me cause I have it from my old server. :)

**Comment by N8teZero** [comment]
This is a good suggestion.

We had this previously, will look into re-adding it to our clothing stores.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
