### ISSUE TITLE
Suggestion PD Armory price

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#53]
#### Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Lower price for pump shotgun

#### Reason: Why would your suggestion be a good addition to Legacy?
Pump shotgun is too expensive currently 120k for each.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion approved. My mistake for putting one too many zeros on that price tag. 😄
