### ISSUE TITLE
Bug: EMS paychecks and boss menu

### ISSUE THREAD

**Issue by Manyfeso** [InZidiuZ/LegacyRP-feedback#54]
Reporter: Manyfeso#8819

Summary: EMS still doesn't get theirs paychecks + EMS boss menu is broken now

Steps to Reproduce: nothing | tried to get to EMS boss menu

Expected Results: fixed paychecks | fixed boss menu

Actual Results: no paychecks | no boss menu

**Comment by InZidiuZ** [comment]
Paychecks have been resolved, although what do you mean a "broken boss menu"? Please fill out future bug-reports as extensively as you can.
