### ISSUE TITLE
Bank private accounts doesnt get 2%

### ISSUE THREAD

**Issue by Haan070** [InZidiuZ/LegacyRP-feedback#55]
Reporter: Haan070

Summary: People make an Private account. So if the put 100K in it. The Next day he will get 2k on his private account added.

Everything is working, only the intrest is not comming on the private accounts

**Comment by InZidiuZ** [comment]
I just did a test, and it seems to work without any issues. If the problem persists, please reopen the issue. For future reports, please fill out the entire template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
