### ISSUE TITLE
Suggestion PD SWAT SHIELD

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#56]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add a swat shield
https://forum.fivem.net/t/release-police-shield/116095

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the swat team since they are missing one at the moment.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by InZidiuZ** [comment]
Suggestion disapproved, because of [this](https://gyazo.com/df04c6e13302250a29234d23bffb49b3).
