### ISSUE TITLE
Suggestion PD chopper

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#57]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add new chopper for PD
https://www.gta5-mods.com/player/swat-team-replacer-fictional-aka-just-for-show

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay to the PD for special operations.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
