### ISSUE TITLE
suggestion Panic button

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#58]
####  Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

#### Summary: Write a short summary of what your suggestion is about.
Add panic button for PD.
https://forum.fivem.net/t/release-police-backup-sets-waypoint-clean-layout-display-1-0/189439

#### Reason: Why would your suggestion be a good addition to Legacy?
Add more Roleplay/realisme to the PD.

#### Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
