### ISSUE TITLE
PD cant Revive. Revive option missing

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#6]
- What happens? (please give a detailed explanation)
PD cant Revive. Revive option missing.
- What did you do to cause this?
nothing
- Has it always been like this?
nope
- What server version did this happen on?
6.0
- Please include a screenshot of your F8 console

**Comment by InZidiuZ** [comment]
Enhancement approved. For future reports, please use the appropriate template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
