### ISSUE TITLE
How to escape jail 101

### ISSUE THREAD

**Issue by JusticeGX** [InZidiuZ/LegacyRP-feedback#60]
reporter: Juicy #6002

Summary: there's a bug where you can get out of the prison anytime you want

Steps to Reproduce: when you go to the prison  door select security and then boiling broke and then voila you can get out from the prison but you still serving some times

Expected Results: not able to get out

Actual Results: you can get out :) 

Screenshots :
![unknown](https://user-images.githubusercontent.com/48247814/53807314-39d7ee00-3f8a-11e9-96f2-10b186bcc1f1.png)

**Comment by InZidiuZ** [comment]
You should be getting "You don't have a key to go here!". Do you not get that, at all? I'm unable to reproduce this on my local server.

**Comment by InZidiuZ** [comment]
Unable to replicate, and no more activity from the reporter. This is being closed.
