### ISSUE TITLE
New MAZDA RX-7 BUGS AND SUGGESTIONS 

### ISSUE THREAD

**Issue by Boblishky** [InZidiuZ/LegacyRP-feedback#61]
Reporter: Boblishky#6918

Summary: When i store my mazda the spoiler is gone which i dont mind but also the livery gets added .

Steps to Reproduce: store the mazda in the garage and the livery will be added . 

Expected Results: The livery will no more be added to the after the car is stored . Also i would like the spoiler to be removed as a option not after it gets stored or repaired .

Actual Results: Fixing the livery bug and adding the non-spoiler option.

More Info

Screenshots: the mazda has a livery and no spolier .

Game Resolution: the car not changing after stored in the garage .

Notes: PLZ add a non spoiler version .

**Comment by N8teZero** [comment]
Thanks for submitting this bug.

We don't currently have a vehicle developer to fix some of these issues with the custom cars. Will explore these fixes when able.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
