### ISSUE TITLE
Everything from my apartment disappeared.

### ISSUE THREAD

**Issue by Marcus2003** [InZidiuZ/LegacyRP-feedback#62]
**Reporter:**
Who is reporting this? Please include discord name.

**Summary:**
Write a short summary of what you're experiencing.

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment]
Please fill out the entire template.

**Comment by InZidiuZ** [comment]
This is being closed due to reporter failing to fill out the template.
