### ISSUE TITLE
Suggestion EMS Trunk

### ISSUE THREAD

**Issue by JanniDummy** [InZidiuZ/LegacyRP-feedback#63]
**Suggester:**
JanniDummy#9924
 
**Summary:**
I would think it would be great if you would be able to actually put someone into the back of the ambulance. As the Option to hide in the trunk is already there I believe its maybe possible to add that.
 
**Reason:**
I believe this would greatly enhance the roleplay aspect of being revived, so you could maybe transport someone to the hospital to do an OP on them, if they got shot in the stomach.
 
**Economy:**
Will have no influence.

**Comment by N8teZero** [comment]
This is a good suggestion.

I'll look into the ability to transport patients easier for better roleplay.

Thanks,
*Nateღ - LegacyRP Staff & Developer*

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. The medical systems in the new framework will add improvement to medical teams, so this should be something more possible.

**Nateღ**
_Legacy RP Staff & Developer_
