### ISSUE TITLE
Bug: EMS Boss menu

### ISSUE THREAD

**Issue by Manyfeso** [InZidiuZ/LegacyRP-feedback#64]
Reporter: Manyfeso#8819

Summary: EMS boss menu doesn't show up

Steps to Reproduce: Tried to get into boss menu

Expected Results: fixed boss menu

Actual Results: Boss menu won't show up. (in the picture there should be also boss menu option)
![BOSS menu](https://user-images.githubusercontent.com/47928522/54073828-d6043c80-428b-11e9-8fe4-d70c62b6dde2.png)

**Comment by InZidiuZ** [comment]
The boss menu was removed as its only purpose was to manage salaries. As salaries are now managed by "the government", and no longer the EMS, it was removed. I believe this was stated in #server-changelogs too.
