### ISSUE TITLE
Police Cars Unable to Catch Criminals 

### ISSUE THREAD

**Issue by SuperDankDizzzle** [InZidiuZ/LegacyRP-feedback#65]
At first it was fantastic when people didnt have the money to fully upgrade their cars and befor the GTR, BMW and AUDI as they are much faster than the PD vehicles - It was never overpowerd for the PD prior to these vehicles coming in and persuits where lasting 10-15 minuts most times and they where fun and intense - now people are literally cop baiting with the new vehicles and taking the piss out of as they know we wont catch them - PD are starting to become more aggressive due to this and overall its having a negative impact on the criminal community as they are no longer fearful of the PD.

**Comment by SuperDankDizzzle** [comment]
A suggestion would be to make the new cars a little slower and the PD cars a little faster

**Comment by N8teZero** [comment]
This is a good suggestion.

We do need to look into the handling of some of the vehicles, especially the customs. We don't have a vehicle dev at the moment, so making these adjustments will take some time unfortunately.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
