### ISSUE TITLE
/reskin Command

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/LegacyRP-feedback#66]
**Suggester:**
Nate

**Summary:**
A command issued by staff that gives the character creation menu back to the player. */reskin <ID>*

**Reason:** Lately there have been a lot of new players joining at the same time and sometimes they get kicked out of the menu. I normally tell them to relog to make a new character, but it would be easier if staff can give them the menu again.

**Comment by InZidiuZ** [comment]
Suggestion approved.
