### ISSUE TITLE
Taxi Contact

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/LegacyRP-feedback#69]
**Reporter:**
Nate

**Summary:**
Taxi contact is not available with Police, EMS, and Mechanic. Taxi should be contactable the same way as other jobs.

https://i.gyazo.com/thumb/1200/6a9e6ebacdf2e46dfe305c76f10bd8a9-png.jpg

**Comment by InZidiuZ** [comment]
This issue has been resolved.
