### ISSUE TITLE
Prison visitation not working

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#7]
- What happens? (please give a detailed explanation)
When you enter jail to visit your friend you get the option to enter, but when you want to leave, you get two option one for jail and one for Boiling broke. The problem is that if you choose jail you will go in jail. and if you choose Boiling broke it will say that you dont have the key for it. Which means that you are stuck
- What did you do to cause this?
Enter Jail visit
- Has it always been like this?
nope
- What server version did this happen on?
6.0
- Please include a screenshot of your F8 console

**Comment by InZidiuZ** [comment]
This issue have been resolved. If the problem persists, please reopen the issue. For future reports, please use the correct template, found in the README file [here](https://github.com/InZidiuZ/LegacyRP-feedback).
