### ISSUE TITLE
Suggestion: House Robberies

### ISSUE THREAD

**Issue by devicy** [InZidiuZ/LegacyRP-feedback#70]
**Suggester:**
Jax Sloan(devicy#0005 (tag could change if nitro runs out)

**Summary:**
In short, ive seen on other servers, like robbing houses, like getting lockpick then
you can go and rob stuff from that house, if you make to much noise the person in there
wakes up and alerts police/tries to get you out.

**Reason:**
It would be a good addition, because it adds another aspect to crimerp, its cool as shit
to do, and it would be useful for crims, and you could do advanced lockpicks for 
bigger houses, and normal lockpick for like hood/sub houses

**Economy:**
Well obvious you make it more RNG sort of, and depending on the house it would give
less/more, but it shouldnt really affect the economy, just put it to a median price with
the current economy.

**Comment by N8teZero** [comment]
This is a good suggestion, but I don't think it's something we will have added for awhile due to the complexity and issues that could arise around it. We'll explore this down the road.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
