### ISSUE TITLE
EMS Clcok in and Clock out

### ISSUE THREAD

**Issue by Haan070** [InZidiuZ/LegacyRP-feedback#71]
Want to have a clock in and clock out system on the Ems. 

Why this system: So they can do something with there money, and doesn't have too switch with there character to be a normal Civilian. 

Also, they don't have to be active on the whole duty and clock off when they want a little break

**Comment by N8teZero** [comment]
Thanks for the suggestion, closing this one as another was posted with the same requests.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
