### ISSUE TITLE
Personal Stash in home/apartments

### ISSUE THREAD

**Issue by SkidRoux** [InZidiuZ/LegacyRP-feedback#73]
Reporter: Who is reporting this? Please include discord name.
🍣𝚂𝚔𝚒𝚍𝚁𝚘𝚞𝚡- 先輩

Summary: Write a short summary of what you're experiencing.
I been farming all morning roughly 5 Hours, I put all my weed in my house and now, they're all gone. All my work gone to waste.

Steps to Reproduce: Include what steps that are needed in order to reproduce the issue.
Put items in home storage and log off and join a different server, and or rejoin to see if the items are still there. This is also a rollback issue and it may not be server sided rollback but definitely rollback in the database where hopping servers before syncing and saving character data.

Expected Results: What are the expected results?

Actual Results: What are the actual results?
I lose interest in grinding until this is fixed. I have high hopes and potential in the development of Legacy RP. I will sticking around and witnessing the progression. I do what i cant to contribute to the community to help make it better. If i am not able to donate, my feed backs matter.

**Comment by N8teZero** [comment]
Thank you for reporting this bug.

We'll continue to monitor this issue. If it continues, please file a compensation request on the forums. 

Thanks,
*Nateღ - LegacyRP Staff & Developer*
