### ISSUE TITLE
Lost $50k when I re logged

### ISSUE THREAD

**Issue by QuagerDoodle** [InZidiuZ/LegacyRP-feedback#75]
**Reporter:**
Who is reporting this? Please include discord name.  Quager#9234

**Summary:**
Write a short summary of what you're experiencing. Re logged to a dif server and when i logged in, I lost $50k

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue. Not sure

**Expected Results:**
What are the expected results? Expecting to get my $50k refunded

**Actual Results:**
What are the actual results?

## More Info

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution? 1920x1080 full screen

**Player Data:**
Write /info whilst ingame and provide the information you're given.

https://gyazo.com/ac6b62df2da509a6d8c2c2e635ffe920

**Notes:**
For anything else noteworthy.

**Comment by QuagerDoodle** [comment]
Logged on yesterday as well, lost $20k which was in the bank

**Comment by N8teZero** [comment]
Thank you for reporting this bug.

This issue was reported awhile back, hopefully you were able to get compensation. If it continues, please file a compensation request on the forums. 

Thanks,
*Nateღ - LegacyRP Staff & Developer*
