### ISSUE TITLE
Suggestion: EMS and PD have their own IG chat

### ISSUE THREAD

**Issue by HALALsnackbar** [InZidiuZ/LegacyRP-feedback#78]
Suggested by: HALALsnackbar#6014

Summary: The ems and pd jobs should have their own chat that only they can use. /ems and /lpd

Reason: This would help with dispatching as well as to communicate with your fellow coworkers i.e "I'm responding to call (gps coord) and I'm 3mi away". Supervisors could do rollcalls to see whos on-duty in that specific server which would help them plan out where people need to be for best coverage to reduce reponse times.

Economy: Shouldnt have an affect on the economy.

**Comment by HALALsnackbar** [comment]
Another use case: I have been on a call for the past 5 minutes and multiple other calls have come in. I have no idea if another EMS has taken these calls but with chat I can scroll up and check to see if anyone has. Maybe require them to enter their callsign as well i.e. "/ems 264 responding to 62.5". I believe this actually adds to the RP experience as well.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. We will look into have some sort of in-game dispatch/CAD to make communication between emergency services more easy.

**Nateღ**
_Legacy RP Staff & Developer_
