### ISSUE TITLE
Lost Car Upon Purchase

### ISSUE THREAD

**Issue by villainhq** [InZidiuZ/LegacyRP-feedback#79]
Reporter: IC [John Wilder] Discord [Villain#1746]

Summary: Bought a Reaper at the Dealership for $385k, money was withdrawn, no car spawned. Checked garage, not there. Relogged. Checked garage again, still nothing there.

Steps to Reproduce: Don't have enough money to try again.

Expected Results: N/A

Actual Results: N/A

**Comment by N8teZero** [comment]
Thank you for reporting this.

All compensation requests are handled on the forums here:  https://legacyroleplay.online/c/support

Thanks,
*Nateღ - LegacyRP Staff & Developer*
