### ISSUE TITLE
Lawyer missing in the F10 menu

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#8]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
Add lawyer to the F10 menu

Reason: Why would your suggestion be a good addition to Legacy?
So PD or civilians can see if there is any lawyer online

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope.

**Comment by InZidiuZ** [comment]
Suggestion approved.
