### ISSUE TITLE
Tailor work outfit bugged

### ISSUE THREAD

**Issue by Pixstrad** [InZidiuZ/LegacyRP-feedback#80]
**Reporter:**
Pixstrad

**Summary:**
Tailor outfit shows a Sheriff's office shirt, and undershirt clips through: 
 
**Steps to Reproduce:**
Take tailor job, go to tailor locker room, equip outfit
 
**Expected Results:**
That the tailor outfit not look like a Sheriff, and that the undershirt doesn't clip through
 
**Actual Results:**
The screenshot you see below
 
**Screenshots:**
https://vgy.me/3d9F7i.jpg
 
**Game Resolution:**
2560x1440
 
**Player Data:**
Version 6.1.0
Commands loaded: 43

**Comment by N8teZero** [comment]
Thank you for reporting this bug.

I have noticed many of the jobs have incorrect uniforms due to the EUP police outfits. We will work on getting these fixed.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
