### ISSUE TITLE
Move AOP (Area of play) to Blaine Country

### ISSUE THREAD

**Issue by Tebroni** [InZidiuZ/LegacyRP-feedback#81]
**Suggester:**
Tebroni

**Summary:**
Suggesting to more the Roleplay area to Blaine Country. True is i have seen some servers that have only RP area in Blaine Country , and you are not allowed to go to LS. Features are, you can see more players on streets, better overall feeling of full server, 40, but even 64 players , when used full map with LS city is so big area that most of us barely see players on streets and mostly have that lonely feeling.  Maybe you can move some jobs from LS and make this maybe little more living world feeling. 

**Reason:**
It would connect and bond people more, and make feeling of more living server and overall more vivid experience.

**Economy:**
I guess we would need to have moved some jobs and Government. But except that , overall economy should stay untouched.

**Comment by N8teZero** [comment]
Thank you for the suggestion.

I don't believe at this time we will be looking at creating an AOP as we want people to create roleplay all over, and not be restricted. I have seen a lot of cool scenarios come from AOP driven servers, but I don't think we fit into that model at the moment.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
