### ISSUE TITLE
Lost money when i logged out 2 times now

### ISSUE THREAD

**Issue by RefTyy** [InZidiuZ/LegacyRP-feedback#82]
**Reporter:**
ING: Jason BlackWood
Discord: RefTyy#2668

**Summary:**
2 days ago i lost about 25k randomly from my pockets the next day i logged in. i first tought it was an invoice/fine from the police that i 
forgot to pay. but as i logged out yesterday and in today. i went from around 144k to 115k again i lost money from nothing.
The only thing i bought was a phone and a gun back around 6-10k - from what i had so i know i had at least 140k before logging out yesterday
because i died in a store robbery. everyone included in the store robbery died and there were no ems so we all agreed to respawn.

**Steps to Reproduce:**
I got no idea tbh. probably a glitched invoice from the police stealing my cash or something.

**Expected Results:**
What are the expected results?

**Actual Results:**
What are the actual results?

## More Info

**Screenshots:**
https://cdn.discordapp.com/attachments/379621813744959489/559568359088193557/20190325030423_1.jpg
/
If the discord one doesnt work for you heres the same screenshot with a different link:
https://gyazo.com/498f995066010c20ebc26975e2455464

My gang were dead and so were all the cops. - There were no ems on at the time so we all respawned including the cops. 

- I got no screens from the F8 Console as i were logged out and this happend when i logged back into the game.

**Game Resolution:**
1920x1080

**Player Data:**
System: EssentialMode Version 6.1.0
System: essentialMode commands loaded 43

**Notes:**
Not really.

**Comment by N8teZero** [comment]
Thank you for reporting this.

All compensation requests are handled on the forums here:  https://legacyroleplay.online/c/support

Thanks,
*Nateღ - LegacyRP Staff & Developer*
