### ISSUE TITLE
inventory  and property

### ISSUE THREAD

**Issue by zacrum** [InZidiuZ/LegacyRP-feedback#84]
can we please have a visual inventory  and owned property that we can share with our friends and park vehicles at   maybe a key system   and more drugs   allso nerf cops   its way to hard to even rob a bar let alone a store or bank

**Comment by N8teZero** [comment]
Thank you for the suggestion.

We are working most of these things. Stay posted for future updates.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
