### ISSUE TITLE
EMS/PD Off Duty Command

### ISSUE THREAD

**Issue by OriginFacts** [InZidiuZ/LegacyRP-feedback#85]
**Suggester:**
E-410 D. Ortiz (Facts)

**Summary:**
EMS/PD Off Duty Toggle. Ability to type in command to go off duty or on duty. 

**Reason:**
To not confuse new or current users on the status in F10 showing ems or pd online and allows user to perform off duty tasks they do not want connected to employment. 

**Economy:**
This will stop people waiting for ems or expecting revives from PD/EMS. Stop new and existing players from leaving server due to misinformation.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
