### ISSUE TITLE
Free vehicle after first purchase for EMS/Discount phone

### ISSUE THREAD

**Issue by OriginFacts** [InZidiuZ/LegacyRP-feedback#86]
**Suggester:**
E-410 D. Ortiz (Facts)

**Summary:**
EMS Vehicles after first purchase are free and can be retrieved like personal vehicles and dispatched at any hospital. Phones are discounted and purchasable at hospital as it takes time to get another phone.

**Reason:**
To stop broken vehicle system for ems and allow ems to get back on duty faster.

**Economy:**
Vehicles would not need to be purchased by ems more than once and vehicles will cost less to retrieve than to purchase another. When ems dies on job, can revive and get back on duty faster instead of running to the store or bank to get a phone they need to do their jobs.

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. I do not believe we will make vehicles free, as we want people to value them and not crash into random stuff knowing they can get a new one spawned. But we may look at reducing costs in the next system.

**Nateღ**
_Legacy RP Staff & Developer_
