### ISSUE TITLE
toggle filter chat

### ISSUE THREAD

**Issue by OriginFacts** [InZidiuZ/LegacyRP-feedback#88]
**Suggester:**
E-410 D. Ortiz (Facts)
 
**Summary:**
Toggle chat for all, ooc, twitter, dispatch and reports
 
**Reason:**
Separates channels to clean up phone clutter for ems/pd and admins. Can keep rp in rp when swapping to dispatch only or twitter only. Does not require ems/pd to have phones to respond to a call.
 
**Economy:**
Cleans clutter of phone messages between police and ems. Allows admins and dispatch to separate chat to their liking. ooc can be responded to depending on the person willing to help.

**Comment by OriginFacts** [comment]
Would also like to get some kind of call number on map. Like a order call. 

"Dispatch Call 54: Person is unconscious at location"
"Dispatch Call 55: PD in need of EMS on site."
"Dispatch Call 56: My friend just got into a car accident help!"

Then on the map there will be a signal symbol and a number next to it showing which call is at which location.

**Comment by N8teZero** [comment]
This is a good suggestion.

I would definitely like to see a way to toggle on and off different chats to make the chat experience more immersive. Would also like to see these chats get incorporated into the phone for a more clean experience. Will add this to our list, though it may be some time as we focus on necessities over enhancements.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
