### ISSUE TITLE
New Siren Control

### ISSUE THREAD

**Issue by BOTMoffatto** [InZidiuZ/LegacyRP-feedback#89]
**Suggester:**
Who is suggesting this? Please include discord name.
 The All-Seeing Nose#0001

**Summary:**
Write a short summary of what your suggestion is about.
 Basically to allow easier siren control. So you will click Q to turn on the lights and then click E to toggle sirens and click R to change tones. This used to be the siren layout on my old server. 

**Reason:**
Why would your suggestion be a good addition to Legacy?
 it is much more simple to understand in my opinion and also adds realism since you wont realistically be holding a siren key to change tone. You will just toggle different siren tones.

**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
It will not effect the economy, at all.

**Comment by N8teZero** [comment]
This is a good suggestion.

I've listed this under enhancements as it isn't a necessity for server improvement and stability, but is something we can explore as time permits. 

Thanks,
*Nateღ - LegacyRP Staff & Developer*
