### ISSUE TITLE
Request for F10 menu

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#9]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
F10 menu when there is none in a whitelisted job it would show up as None.

Reason: Why would your suggestion be a good addition to Legacy?
Example there is server rule 
(2.16) You are not allowed to save your friend from being arrested if there are less than two cops online.
Since people wont be able to see how many there is.
Another example is for lawyers so PD dont have to let the arrested person wait another 5min to verify how ever there is a lawyer active or not.

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Nope.

**Comment by InZidiuZ** [comment]
Suggestion approved.
