### ISSUE TITLE
[Suggestion] Move twitter to phone

### ISSUE THREAD

**Issue by Anderzenn** [InZidiuZ/LegacyRP-feedback#90]
**Suggester:**
Anderzenn (Anderzenn#0069)

**Summary:**
Twitter on the phone could help a lot of people running their "own" businesses as well as make the whole twitter experience a lot better and more realistic whilst removing clutter from the chat giving people less reason to use the chat.

**Reason:**
I think this suggestion could help a ton when it comes to RP and I feel that it adds a lot more options for how people use twitter compared to right now. I feel that people would use it a lot more for how it's meant to be used, currently a lot of people (especially new comers) are spamming twitter with questions out of character. I also think it could help people who run their "own" businesses with advertising their services. It could also add more functionality to twitter compared to what it has right now like images or replies. I know this would require a lot of work but I feel if it is done correctly then it will improve the rp experience for everyone.

**Economy:**
This could have some effects on the economy, perhaps more people will use the taxis? People could advertise them selves as Über drivers or something a long those lines and it would help them make a living. Of course there are other things than just drivers but that was the first thing that came to mind.

**Comment by N8teZero** [comment]
This is a good suggestion.

I would definitely like to see a way to toggle on and off different chats to make the chat experience more immersive. Would also like to see these chats get incorporated into the phone for a more clean experience. Will add this to our list, though it may be some time as we focus on necessities over enhancements.

Thanks,
*Nateღ - LegacyRP Staff & Developer*

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system.

**Nateღ**
_Legacy RP Staff & Developer_
