### ISSUE TITLE
AFK script

### ISSUE THREAD

**Issue by sercanatici** [InZidiuZ/LegacyRP-feedback#91]
Suggester: Who is suggesting this? Please include discord name.
Sercan#1192

Summary: Write a short summary of what your suggestion is about.
Kick people that have been not moving for example 10 mins or more

Reason: Why would your suggestion be a good addition to Legacy?
Removing the people thats afk and not letting others in which want to play

Economy: Will this have an effect on the server's economy. If so, in what way do you believe it will?
Yes, but in a positiv way.

**Comment by N8teZero** [comment]
Thank you for the suggestion.

After some discussions with InZidiuZ, I do not believe we will be adding an auto afk-kick in the near future. There are certain RP situations that could be interrupted with such a feature, and we want to avoid people getting kicked while cuffed or hanging out with friends. Staff will continue to monitor true afk people and kick accordingly.

Thanks,
*Nateღ - LegacyRP Staff & Developer*
