### ISSUE TITLE
Unicorn issues

### ISSUE THREAD

**Issue by tr1ckz** [InZidiuZ/LegacyRP-feedback#92]
Suggester:
Who is suggesting this? Please include discord name.
tr1ck#6660

Summary:
Write a short summary of what your suggestion is about.
Washing money hasn't gone through and it's been around 18 hours since we started it.
Lap dances performed by local staff ($500) doesn't go into the company's account.
Company garage only has a rent-a-car van, any personal care stored in there will go to a default garage and cannot be spawned from the club's menu.

Reason:
Why would your suggestion be a good addition to Legacy?
Staff parking should be a thing to keep cars organized in the club during events. Staff can park their vehicles in the company garage leaving open spots for guests.
Money laundering not working is causing a huge economic issue at the moment.

Economy:
Will this have an effect on the server's economy. If so, in what way do you believe it will?
Unable to do much without any income, can't host events or help people with they dirty money since we've been waiting for a while for it to go through.

**Comment by N8teZero** [comment]
Thank you for reporting this bug.

We have noticed issues with the money wash for other businesses as well. We do believe that the washed money is saved in the database still, just hasn't been pushed through to clean money. Will investigate further.

Thanks,
*Nateღ - LegacyRP Staff & Developer*

**Comment by N8teZero** [comment]
I've done some testing and I do believe money washing has been fixed. Please update if you have further issues.
