### ISSUE TITLE
Lockpicking

### ISSUE THREAD

**Issue by StealthyKC** [InZidiuZ/LegacyRP-feedback#94]
**Suggester:**
Who is suggesting this? Please include discord name.
Stealthy#6357
**Summary:**
Write a short summary of what your suggestion is about.
Making all local vehicles locked and introducing a lockpicking system which could be extended into robbing houses and chop-shopping stolen vehicles. Limit how many vehicles the chopshop will take per player for a duration of time to keep the economy stable but add another source of income.
**Reason:**
Why would your suggestion be a good addition to Legacy?
Adding other sources of income aside from selling weed can create more storylines for other roleplayers and will boost the economy so players can further enjoy the additions on the servers (exotic cars, houses). Lockpicking will be another thing cops can be on the lookout for with car alarms or alarms from houses being broken into. 
**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
It will add another potential source of income with chop shopping vehicles or breaking into houses to rob using lockpicks. It will boost the economy greatly but not crazy amounts if you restrict how many vehicles you can chop in a certain time gap.

**Comment by N8teZero** [comment]
Thank you for the suggestion.

We will explore adding these features to the game to enhance criminal RP. 👍 

Thanks,
*Nateღ - LegacyRP Staff & Developer*

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. I have coded scripts to allow lockpicking of vehicles as most vehicles will be locked. We will work on expanding that to possibly go for houses as well, though this isn't in our current roadmap.

**Nateღ**
_Legacy RP Staff & Developer_
