### ISSUE TITLE
Transport Bug

### ISSUE THREAD

**Issue by cyanmanson** [InZidiuZ/LegacyRP-feedback#95]
**Reporter:**
HSR Hate
ingame name: Eddie Watkins
discord name: @Hate#3694 

**Summary:**
There is an issue with a trailer spawning in at the deliveries spot behind the pet store on route 68

**Steps to Reproduce:**
deliver a load there then try to get another one from the marker

**Expected Results:**
the trailer to be upright

**Actual Results:**
sometimes its on its side, sometimes its on a 45 degree angle

**Screenshots:**
none

**Game Resolution:**
1920*1028

**Player Data:**
i write /info says invalid command....

**Notes:**
nope

**Comment by N8teZero** [comment]
Thank you for reporting this issue.

I have seen some other reports surrounding the spawning of trailers, so I'll go through and check all locations and make sure they are setup in clear coordinates.

Thanks,
*Nateღ - LegacyRP Staff & Developer*

**Comment by N8teZero** [comment]
The spawn point for this and other trailers has been fixed. If you find others in bad spots, let us know.

Thanks,
Nateღ - LegacyRP Staff & Developer
