### ISSUE TITLE
EMS boss menu

### ISSUE THREAD

**Issue by JMcFluffy** [InZidiuZ/LegacyRP-feedback#96]
Reporter: Lil TW#9255

Screenshot
![54073828-d6043c80-428b-11e9-8fe4-d70c62b6dde2](https://user-images.githubusercontent.com/49207984/55430493-8bc26280-558e-11e9-9e55-f2d7de947f71.png)

Summary: EMS boss menu doesn't show up

Steps to Reproduce: Tried to get into boss menu

Expected Results: fixed boss menu

Actual Results: Boss menu won't show up. (in the picture there should be also boss menu option)
BOSS menu

**Comment by JMcFluffy** [comment]
also the locker room is broken, the clothes are wrong

**Comment by Anderzenn** [comment]
#64 
> The boss menu was removed as its only purpose was to manage salaries. As salaries are now managed by "the government", and no longer the EMS, it was removed. I believe this was stated in #server-changelogs too.
