### ISSUE TITLE
Inventory of house.

### ISSUE THREAD

**Issue by teheenew** [InZidiuZ/LegacyRP-feedback#97]
-**Reporter:**
Who is reporting this? Please include discord name.
Teheenew#3124
**Summary:**
Write a short summary of what you're experiencing.
so I am in abit of trouble, I store up stuff in my inventory of my house, the server resets and my items are gone, now after that all I relog and the Items re-appear, but u cannot longer take them out. Giving me a warning the item is not in the property. This only occurs when a server restart happens. (I don't know how much time before hand is lost when a restart happens). Like how much rollback is happening, but character stands on same spot after a restart so I am kinda stuck that how the inventory of your appertment is abit bugged.
So whenever I store 15 weed , server restart, 15 weed is lost but I keep storing, I get this -> http://prntscr.com/n6kf0j
Now today whenever I logged in this appeared ->https://prnt.sc/n6x6i6
I can tell you inbefore it was 30 but after relogging from a big relog like sleep / work etc, it's just gets lowered/raised to the amount that is put in after the restart. but still not able to take it out of the property, ->http://prntscr.com/n6x76h 
Ps. inventory taken when I tried to pick out the 2 bugged marijuana that was inbefore 30... 
http://prntscr.com/n6x7h4
http://prntscr.com/n6erkq

I've seen someone else say this also. Reason why I tested this fully out with screenies, been doing this from 2days ago.

To make sure after today; Restart was 16:20~ https://prnt.sc/n6z842
 https://prnt.sc/n6y4nb

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce the issue.
It's coding for sure, don't know if it could be fixed or not.
**Expected Results:**
What are the expected results?
I hope to get this fixed but that's up to you the develop-team.
**Actual Results:**
What are the actual results?
That Restarts no longer cause any trouble with inventory slots in houses / appertments / mansions. so on.
## More Info

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.
Provided Screenshots that were taken with lightshot within the text.
**Game Resolution:**
What is your game's resolution?
No need. Ingame isseu.
**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.
Teheenew/Del PePe

**Comment by N8teZero** [comment]
Hey, Sorry to hear this happened. We've been seeing some issue with the syncing of housing storage across servers and restarts. To get this taken care of by an admin, please submit a compensation request on our forums. https://legacyroleplay.online/c/support

Thanks,
*Nateღ - LegacyRP Staff & Developer*
