### ISSUE TITLE
Suggestion For Custom Clothes.

### ISSUE THREAD

**Issue by BOTMoffatto** [InZidiuZ/LegacyRP-feedback#98]
**Suggester:**
Who is suggesting this? Please include discord name.
M1#0001
 
**Summary:**
Write a short summary of what your suggestion is about.
It is just to add custom clothes to the store, there are only police clothes available and some cosplay outfits that not alot of people use. Adding like branded and designer clothes like adidas, nike, gucci, north face etc will add some more customisation and realistic clothes (Shoes, Shirts, T-Shirts, Hoddies, pants etc)
 
**Reason:**
Why would your suggestion be a good addition to Legacy?
it will add some more customisation and realistic clothes since some of the clothes existing are either vanilla GTA clothes or are police or unusable clothes for normal civs like military clothes or are not used as much like the cosplay clothes

**Economy:**
Will this have an effect on the server's economy. If so, in what way do you believe it will?
It wont have an effect on the economy since buying an outfit will still be $250, all it will be adding is more options

**Comment by N8teZero** [comment]
Hey,

I am archiving this bug/suggestion to add to our development list. We are putting our focus on OP-Framework which will have many improvements over the current system. We'll be looking at adding custom clothing, as well as moving the EUP police outfits out of the stores so it doesn't overwrite most of the civilian clothes.

**Nateღ**
_Legacy RP Staff & Developer_
