### ISSUE TITLE
Fire Department In The Server

### ISSUE THREAD

**Issue by Keezup** [InZidiuZ/LegacyRP-feedback#99]
I think a Fire Department should be added or merged with the ems department to the server because in situations like fires and car crashes ems can't really do much but with a fire department that'll really improve roleplay. Also If there will be a fire department there should be a good fire script so fires don't just go out really quick. Suggested by FearlessOregon1#0209

**Comment by N8teZero** [comment]
Great suggestion,

I am working on adding a Fire & Rescue Division within the EMS jobs. Still some logistical things to work out, and higher priority issues, but it is on the agenda.

Thanks,
Nateღ - LegacyRP Staff & Developer
